// Snowball Battle — sprite data. OWNED BY DESIGN (see design/DESIGN.md).
// Format: one char = one pixel. '.' = transparent. H/h/S/s = team colours (swapped by engine).
// Generated from the designer's source; hand edits are fine — keep row length == w, rows == h.

export const PALETTE = {
  ".": null,
  "k": "#1a1c2c",
  "K": "#3b4468",
  "n": "#5d6f9e",
  "B": "#8fa7cf",
  "b": "#bfd2ea",
  "o": "#e4eef8",
  "w": "#ffffff",
  "f": "#f8c9a0",
  "F": "#d99670",
  "p": "#ee8f8f",
  "j": "#4f7ccc",
  "J": "#33539a",
  "y": "#f5b83d",
  "Y": "#ffe27a",
  "t": "#8c5a35",
  "T": "#573522",
  "e": "#dcb784",
  "g": "#3f8a72",
  "G": "#24594f",
  "d": "#163a3a",
  "c": "#f07c34",
  "C": "#b14e1f",
};

// GREEN = high-value lime + bobble beanie with pompom (bottom team, back view).
// RED   = low-value crimson + trapper hat with white fur brim & earflaps (top team, front view).
export const TEAM_COLORS = {
  green: {"H": "#a6e85c", "h": "#4fa446", "S": "#a6e85c", "s": "#4fa446"},
  red: {"H": "#d63a4f", "h": "#8a1f3c", "S": "#d63a4f", "s": "#8a1f3c"},
};

export const TEAM_CHARS = 'HhSs';

export const SPRITES = {
  kid_front_idle: { w: 14, h: 16, anchor: [7, 15], fps: 2, frames: [
    [
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '..khpffffphk..',
      '...kSSSSSSk...',
      '..kjSsjjjjJk..',
      '.kjjSsjjjjJJk.',
      '.kyjsSjjjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..............',
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '..khpffffphk..',
      '...kSSSSSSk...',
      '.kjjSsjjjjJJk.',
      '.kyjsSjjjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_front_windup: { w: 14, h: 16, anchor: [7, 15], fps: 1, note: "hold 180-260 ms, then play throw", frames: [
    [
      '.....kkkk..kk.',
      '....kHHHHkkwwk',
      '...kHHHHHHkwbk',
      '..kwwwwwwwwkyk',
      '..kHffffffHkyk',
      '..kHfkffkfHkjk',
      '..khpffffphkjk',
      '...kSSSSSSk.jk',
      '..kjSsjjjjJJjk',
      '.kjjSsjjjjJk..',
      '.kyjsSjjjjJk..',
      '.kykjjjjjjJk..',
      '..kkKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_front_throw: { w: 14, h: 16, anchor: [7, 15], fps: 10, note: "release on frame 0: ball at anchor + (1,-6) i.e. ground x+1, z=6", frames: [
    [
      '..............',
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '..khpfkkfphk..',
      '...kSSSSSSk...',
      '.kjjSsjkyykJk.',
      '.kyjsSjkyyJJk.',
      '.kykjjjjkkkk..',
      '..kkKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..............',
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '..khpffffphk..',
      '...kSSSSSSk...',
      '.kjjSsjjjjJk..',
      '.kyjsSjjJJJk..',
      '.kykjjjkyyk...',
      '..kkKKKkyyk...',
      '...kKKkkkkk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_front_hit: { w: 14, h: 16, anchor: [7, 15], fps: 8, frames: [
    [
      '..............',
      'B....kkkk.....',
      '....kHHHHk..B.',
      '...kHHHHHHk...',
      '..kwwwwwwwwk.B',
      '..kHwwwwffHk..',
      'B.kHwbwwkfHk..',
      '..khpwwbfphk..',
      '...kSSSSSSk...',
      '..kjSsjjjjJk..',
      '.kjjSsjjjjJJk.',
      '.kyjsSjjjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..B...kkkk....',
      '.....kHHHHk...',
      'B...kHHHHHHk..',
      '...kwwwwwwwwk.',
      '...kHwwwwffHk.',
      '...kHwbwwkfHk.',
      '...khpwwbfphk.',
      '....kSSSSSSk..',
      '...kjSsjjjjJk.',
      '..kjjSsjjjjJJk',
      '..kyjsSjjjjJyk',
      '..kykjjjjjjkyk',
      '...kkKKKKKKkk.',
      '....kKKkkKKk..',
      '...kTTTkkTTTk.',
      '...kkkk..kkkk.',
    ],
  ] },
  kid_front_cheer: { w: 14, h: 16, anchor: [7, 15], fps: 6, frames: [
    [
      '..............',
      '.kk..kkkk..kk.',
      'kyykkHHHHkkyyk',
      'kyykHHHHHHkyyk',
      'kjkwwwwwwwwkjk',
      'kjkHffffffHkjk',
      'kjkHfkffkfHkjk',
      'kjkhpfkkfphkjk',
      '.kjkSSSSSSkjk.',
      '..kjSsjjjjJk..',
      '..kjsSjjjjJk..',
      '..kjjjjjjjJk..',
      '...kKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '.kk..kkkk..kk.',
      'kyykkHHHHkkyyk',
      'kyykHHHHHHkyyk',
      'kjkwwwwwwwwkjk',
      'kjkHffffffHkjk',
      'kjkHfkffkfHkjk',
      'kjkhpfkkfphkjk',
      '.kjkSSSSSSkjk.',
      '..kjSsjjjjJk..',
      '..kjsSjjjjJk..',
      '..kjjjjjjjJk..',
      '...kKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
      '..............',
    ],
  ] },
  kid_front_duck: { w: 14, h: 16, anchor: [7, 15], fps: 2, frames: [
    [
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '.kyhpffffphyk.',
      '.kykSSSSSSkyk.',
      '.kKKjjjjjjKKk.',
      '.kTTkkkkkkTTk.',
    ],
    [
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHkffkffHk..',
      '.kyhpffffphyk.',
      '.kykSSSSSSkyk.',
      '.kKKjjjjjjKKk.',
      '.kTTkkkkkkTTk.',
    ],
  ] },
  kid_back_idle: { w: 14, h: 16, anchor: [7, 15], fps: 2, frames: [
    [
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '..kHHhHHhHHk..',
      '..khhhhhhhhk..',
      '..kFttttttFk..',
      '...kSSSSSSk...',
      '..kjjjSsjjJk..',
      '.kjjjjsSjjJJk.',
      '.kyjjjSsjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..............',
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '..kHHhHHhHHk..',
      '..khhhhhhhhk..',
      '..kFttttttFk..',
      '...kSSSSSSk...',
      '.kjjjjsSjjJJk.',
      '.kyjjjSsjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_back_windup: { w: 14, h: 16, anchor: [7, 15], fps: 1, note: "hold 180-260 ms, then play throw", frames: [
    [
      '......kk...kk.',
      '.....kwwk.kwwk',
      '....kHbbHkkwbk',
      '...kHHHHHHkkyk',
      '..kHHhHHhHHkyk',
      '..khhhhhhhhkjk',
      '..kFttttttFkjk',
      '...kSSSSSSk.jk',
      '..kjjjSsjjJJjk',
      '.kjjjjsSjjJk..',
      '.kyjjjSsjjJk..',
      '.kykjjjjjjJk..',
      '..kkKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_back_throw: { w: 14, h: 16, anchor: [7, 15], fps: 10, note: "release on frame 0: ball at anchor + (5,-13) i.e. ground x+5, z=13", frames: [
    [
      '......kk...kk.',
      '.....kwwk.kyyk',
      '....kHbbHkkyyk',
      '...kHHHHHHkjjk',
      '..kHHhHHhHHkjk',
      '..khhhhhhhhkjk',
      '..kFttttttFkjk',
      '...kSSSSSSkjk.',
      '..kjjjSsjjJjk.',
      '.kjjjjsSjjJk..',
      '.kyjjjSsjjJk..',
      '.kykjjjjjjJk..',
      '..kkKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..............',
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '..kHHhHHhHHk..',
      '..khhhhhhhhk..',
      '..kFttttttFk..',
      '...kSSSSSSk...',
      '..kjjjSsjjJk..',
      '.kjjjjsSjjJJk.',
      '.kyjjjSsjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_back_hit: { w: 14, h: 16, anchor: [7, 15], fps: 8, frames: [
    [
      'B.....kk......',
      '.....kwwk...B.',
      '....kHbbHk....',
      '...kwwwHHHk..B',
      '..kwwbwwhHHk..',
      'B.kwbwwhhhhk..',
      '..kFwwttttFk..',
      '...kSSSSSSk...',
      '..kjjjSsjjJk..',
      '.kjjjjsSjjJJk.',
      '.kyjjjSsjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..B...........',
      'B.....kk......',
      '.....kwwk.....',
      '....kHbbHk...B',
      '...kwwwHHHk...',
      '..kwwbwwhHHk..',
      '..kwbwwhhhhk..',
      '..kFwwttttFk..',
      '...kSSSSSSk...',
      '..kjjjSsjjJk..',
      '.kjjjjsSjjJJk.',
      '.kyjjjSsjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_back_cheer: { w: 14, h: 16, anchor: [7, 15], fps: 6, frames: [
    [
      '..............',
      '.kk...kk...kk.',
      'kyyk.kwwk.kyyk',
      'kyykkHbbHkkyyk',
      'kjkHHHHHHHHkjk',
      'kjkHHhHHhHHkjk',
      'kjkhhhhhhhhkjk',
      'kjkFttttttFkjk',
      '.kjkSSSSSSkjk.',
      '..kjjjSsjjJk..',
      '..kjjjsSjjJk..',
      '..kjjjjjjjJk..',
      '...kKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '.kk...kk...kk.',
      'kyyk.kwwk.kyyk',
      'kyykkHbbHkkyyk',
      'kjkHHHHHHHHkjk',
      'kjkHHhHHhHHkjk',
      'kjkhhhhhhhhkjk',
      'kjkFttttttFkjk',
      '.kjkSSSSSSkjk.',
      '..kjjjSsjjJk..',
      '..kjjjsSjjJk..',
      '..kjjjjjjjJk..',
      '...kKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
      '..............',
    ],
  ] },
  kid_back_duck: { w: 14, h: 16, anchor: [7, 15], fps: 2, frames: [
    [
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '.kyHHhHHhHHyk.',
      '.kyhhhhhhhhyk.',
      'kjkFttttttFkjk',
      'kjjkSSSSSSkjjk',
      '.kjjjjsSjjjJk.',
      '.kTTkkkkkkTTk.',
    ],
    [
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '.......kk.....',
      '......kwwk....',
      '....kHHbbk....',
      '...kHHHHHHk...',
      '.kyHHhHHhHHyk.',
      '.kyhhhhhhhhyk.',
      'kjkFttttttFkjk',
      'kjjkSSSSSSkjjk',
      '.kjjjjsSjjjJk.',
      '.kTTkkkkkkTTk.',
    ],
  ] },
  ball_small: { w: 4, h: 4, anchor: [2, 2], frames: [
    [
      '.kk.',
      'kwok',
      'kobk',
      '.kk.',
    ],
  ] },
  ball_big: { w: 10, h: 10, anchor: [5, 5], frames: [
    [
      '...kkkk...',
      '.kkwwwokk.',
      '.kwwwoook.',
      'kwwwwooobk',
      'kwwoooobbk',
      'koooooobbk',
      'koooobbbBk',
      '.kobbbbBk.',
      '.kkbbbBkk.',
      '...kkkk...',
    ],
  ] },
  shadow_small: { w: 4, h: 2, anchor: [2, 1], frames: [
    [
      'bBBb',
      '.bb.',
    ],
  ] },
  shadow_big: { w: 10, h: 3, anchor: [5, 1], frames: [
    [
      '..bbbbbb..',
      'bbBBBBBBbb',
      '..bbbbbb..',
    ],
  ] },
  giant_front_idle: { w: 32, h: 40, anchor: [16, 39], fps: 3, frames: [
    [
      '.............kkkkkk.............',
      '...........kkHHHHHHkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHHHHHHHHHhhk.........',
      '........kwwwwwwwwwwwwwbk........',
      '........kwwwwwwwwwwwwbbk........',
      '........kHkkkkkkkkkkkkHk........',
      '........kHkwwwwoooobbkHk........',
      '........khkwwkooookbbkhk........',
      '........khkookooookbbkhk........',
      '.........koooooccccCBBk.........',
      '..........kopoooCCbbpk..........',
      '..TT......kookbbbbbkBk......TT..',
      '..TT......kbbbbkbkBBBk......TT..',
      '.TTT.....k.kkkkkkkkkk..k....TTT.',
      '....t....kssSSssSSssSSsk...t....',
      '.....t...kssSSssSSssSSsk..t.....',
      '......t..kSSkkkkkkkkkkk..t......',
      '.......t.ksSkoooooobbbk.t.......',
      '........kSskoooooobbbBkt........',
      '........ksSkoookkbbbbBt.........',
      '.......kSskooooobbbbBBk.........',
      '.......kSkSooobbbbbBBBk.........',
      '.......k.kkbbbbkkbBBBkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......koooooookkoobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '.............kkkkkk.............',
      '...........kkHHHHHHkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHHHHHHHHHhhk.........',
      '........kwwwwwwwwwwwwwbk........',
      '........kwwwwwwwwwwwwbbk........',
      '........kHkkkkkkkkkkkkHk........',
      '........kHkwwwwoooobbkHk........',
      '........khkwwkooookbbkhk........',
      '........khkookooookbbkhk........',
      '.........koooooccccCBBk.........',
      '..........kopoooCCbbpk..........',
      '..........kookbbbbbkBk..........',
      '..TT......kbbbbkbkBBBk......TT..',
      '..TT.....k.kkkkkkkkkk..k....TT..',
      '.TTT.....kssSSssSSssSSsk....TTT.',
      '....t....kssSSssSSssSSsk...t....',
      '.....tt.kSSkkkkkkkkkkkk..tt.....',
      '.......tksSkwoooooobbbk.t.......',
      '.......kSskooooooobbbBkt........',
      '.......ksSkooookkbbbbBt.........',
      '......kSskoooooobbbbBBk.........',
      '......kSkSoooobbbbbBBBk.........',
      '......k.kkkbbbbkkbBBBkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......koooooookkoobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
  ] },
  giant_front_throw: { w: 32, h: 40, anchor: [16, 39], fps: 6, note: "release frame = 1: spawn ball_big at hand = anchor + (14,-20) (ground x+14, height z=20)", frames: [
    [
      '.............kkkkkk.....kkkk....',
      '...........kkHHHHHHkk.kkwwwokk..',
      '..........kHHHHHHHHHHkkwwwoook..',
      '.........kHHHHHHHHHHHhkwwwooobk.',
      '.........kHHHHHHHHHHhhkwoooobbk.',
      '........kwwwwwwwwwwwwwbkoooobbk.',
      '........kwwwwwwwwwwwwbbkoobbbBk.',
      '........kHkkkkkkkkkkkkHkbbbbBk..',
      '........kHkwwwwoooobbkHkbTbTkk..',
      '........khkwwkooookbbkhkkkTk....',
      '........khkookooookbbkhk..t.....',
      '.........koooooccccCBBk..t......',
      '..........kopoooCCbbpk...t......',
      '..........kookbbbbbkBk...t......',
      '..TT......kbbbbkbkBBBk..t.......',
      '..TT.....k.kkkkkkkkkk..kt.......',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kSSkkkkkkkkkkkt........',
      '.......t.ksSkoooooobbbt.........',
      '........kSskoooooobbbBt.........',
      '........ksSkoookkbbbbBk.........',
      '.......kSskooooobbbbBBk.........',
      '.......kSkSooobbbbbBBBk.........',
      '.......k.kkbbbbkkbBBBkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......koooooookkoobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '.............kkkkkk.............',
      '...........kkHHHHHHkk...........',
      '..........kHHHHHHHHHHk.....B....',
      '.........kHHHHHHHHHHHhk.....b...',
      '.........kHHHHHHHHHHhhk......B..',
      '........kwwwwwwwwwwwwwbk.....B..',
      '........kwwwwwwwwwwwwbbk......b.',
      '........kHkkkkkkkkkkkkHk......B.',
      '........kHkwwwwoooobbkHk.......B',
      '........khkwwkooookbbkhk.......b',
      '........khkookooookbbkhk.......B',
      '.........koooooccccCBBk........B',
      '..........kopoooCCbbpk.........b',
      '..........kookbbbbbkBk........B.',
      '..TT......kbbbbkbkBBBk........B.',
      '..TT.....k.kkkkkkkkkk..k........',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kSSkkkkkkkkkkk........T',
      '.......t.ksSkoooooobbbk...ttttT.',
      '........kSskoooooobbbBtttt.....T',
      '........ksSkoookkbbbbBk.........',
      '.......kSskooooobbbbBBk.........',
      '.......kSkSooobbbbbBBBk.........',
      '.......k.kkbbbbkkbBBBkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......koooooookkoobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '.............kkkkkk.............',
      '...........kkHHHHHHkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHHHHHHHHHhhk.........',
      '........kwwwwwwwwwwwwwbk........',
      '........kwwwwwwwwwwwwbbk........',
      '........kHkkkkkkkkkkkkHk........',
      '........kHkwwwwoooobbkHk........',
      '........khkwwkooookbbkhk........',
      '........khkookooookbbkhk........',
      '.........koooooccccCBBk.........',
      '..........kopoooCCbbpk..........',
      '..........kookbbbbbkBk..........',
      '..TT......kbbbbkbkBBBk..........',
      '..TT.....k.kkkkkkkkkk..k........',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kSSkkkkkkkkkkk.........',
      '.......t.ksSkoooooobbbk.........',
      '........kSskoooooobbbBk.........',
      '........ksSkoookkbbbbBk.........',
      '.......kSskooooobbbbBBt.........',
      '.......kSkSooobbbbbBBBkt........',
      '.......k.kkbbbbkkbBBBkk.t.......',
      '........kwkbbbbbBBBBBkbk.t......',
      '.......kwwwkkBBBBBBkkbbbk.t.....',
      '.......kwwwwwkkkkkkoobbbk..t....',
      '.......kwwwwwooooooobbbbk...TTT.',
      '.......koooooookkoobbbbBk....T..',
      '......kooooooooooobbbbbBBk...T..',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
  ] },
  giant_back_idle: { w: 32, h: 40, anchor: [16, 39], fps: 3, frames: [
    [
      '..............kkkk..............',
      '.............kwwwwk.............',
      '.............kwwwbk.............',
      '...........kkkbbbbkkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '........khhhhhhhhhhhhhhk........',
      '........khhhhhhhhhhhhhhk........',
      '.........kkkkkkkkkkkkkk.........',
      '.........kooooooobbbBBk.........',
      '..........kooooobbbbBk..........',
      '..TT......kooobbbbbBBk......TT..',
      '..TT......kbbbbbbBBBBk......TT..',
      '.TTT.....k.kkkkkkkkkk..k....TTT.',
      '....t....kssSSssSSssSSsk...t....',
      '.....t...kssSSssSSssSSsk..t.....',
      '......t..kkkkkkkkkSSkkk..t......',
      '.......t.kwwwooooksSkbk.t.......',
      '........tkoooooookSskBkt........',
      '.........tooooooobksSkt.........',
      '.........koooooobbkSskk.........',
      '.........koooobbbbkSkSk.........',
      '.........kkbbbbbbbBBkkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......kooooooooooobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '..............kkkk..............',
      '.............kwwwwk.............',
      '.............kwwwbk.............',
      '...........kkkbbbbkkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '........khhhhhhhhhhhhhhk........',
      '........khhhhhhhhhhhhhhk........',
      '.........kkkkkkkkkkkkkk.........',
      '.........kooooooobbbBBk.........',
      '..........kooooobbbbBk..........',
      '..........kooobbbbbBBk..........',
      '..TT......kbbbbbbBBBBk......TT..',
      '..TT.....k.kkkkkkkkkk..k....TT..',
      '.TTT.....kssSSssSSssSSsk....TTT.',
      '....t....kssSSssSSssSSsk...t....',
      '.....tt..kkkkkkkkkkSSkk..tt.....',
      '.......t.kwwwoooooksSkk.t.......',
      '........tkooooooookSskkt........',
      '.........tooooooobbksSk.........',
      '.........koooooobbbkSsk.........',
      '.........koooobbbbbkSkS.........',
      '.........kkbbbbbbbBBBkkk........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......kooooooooooobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
  ] },
  giant_back_throw: { w: 32, h: 40, anchor: [16, 39], fps: 6, note: "release frame = 1: spawn ball_big at hand = anchor + (14,-20) (ground x+14, height z=20)", frames: [
    [
      '..............kkkk......kkkk....',
      '.............kwwwwk...kkwwwokk..',
      '.............kwwwbk...kwwwoook..',
      '...........kkkbbbbkkkkwwwwooobk.',
      '..........kHHHHHHHHHHkwwoooobbk.',
      '.........kHHHHHHHHHHHhkooooobbk.',
      '.........kHHhHHhHHhHhhkooobbbBk.',
      '.........kHHhHHhHHhHhhkobbbbBk..',
      '........khhhhhhhhhhhhhhkbTbTkk..',
      '........khhhhhhhhhhhhhhkkkTk....',
      '.........kkkkkkkkkkkkkk...t.....',
      '.........kooooooobbbBBk..t......',
      '..........kooooobbbbBk...t......',
      '..........kooobbbbbBBk...t......',
      '..TT......kbbbbbbBBBBk..t.......',
      '..TT.....k.kkkkkkkkkk..kt.......',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kkkkkkkkkSSkkkt........',
      '.......t.kwwwooooksSkbt.........',
      '........tkoooooookSskBt.........',
      '.........tooooooobksSkk.........',
      '.........koooooobbkSskk.........',
      '.........koooobbbbkSkSk.........',
      '.........kkbbbbbbbBBkkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......kooooooooooobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '..............kkkk..............',
      '.............kwwwwk.............',
      '.............kwwwbk........B....',
      '...........kkkbbbbkkk.......b...',
      '..........kHHHHHHHHHHk.......B..',
      '.........kHHHHHHHHHHHhk......B..',
      '.........kHHhHHhHHhHhhk.......b.',
      '.........kHHhHHhHHhHhhk.......B.',
      '........khhhhhhhhhhhhhhk.......B',
      '........khhhhhhhhhhhhhhk.......b',
      '.........kkkkkkkkkkkkkk........B',
      '.........kooooooobbbBBk........B',
      '..........kooooobbbbBk.........b',
      '..........kooobbbbbBBk........B.',
      '..TT......kbbbbbbBBBBk........B.',
      '..TT.....k.kkkkkkkkkk..k........',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kkkkkkkkkSSkkk........T',
      '.......t.kwwwooooksSkbk...ttttT.',
      '........tkoooooookSskBtttt.....T',
      '.........tooooooobksSkk.........',
      '.........koooooobbkSskk.........',
      '.........koooobbbbkSkSk.........',
      '.........kkbbbbbbbBBkkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......kooooooooooobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '..............kkkk..............',
      '.............kwwwwk.............',
      '.............kwwwbk.............',
      '...........kkkbbbbkkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '........khhhhhhhhhhhhhhk........',
      '........khhhhhhhhhhhhhhk........',
      '.........kkkkkkkkkkkkkk.........',
      '.........kooooooobbbBBk.........',
      '..........kooooobbbbBk..........',
      '..........kooobbbbbBBk..........',
      '..TT......kbbbbbbBBBBk..........',
      '..TT.....k.kkkkkkkkkk..k........',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kkkkkkkkkSSkkk.........',
      '.......t.kwwwooooksSkbk.........',
      '........tkoooooookSskBk.........',
      '.........tooooooobksSkk.........',
      '.........koooooobbkSskt.........',
      '.........koooobbbbkSkSkt........',
      '.........kkbbbbbbbBBkkk.t.......',
      '........kwkbbbbbBBBBBkbk.t......',
      '.......kwwwkkBBBBBBkkbbbk.t.....',
      '.......kwwwwwkkkkkkoobbbk..t....',
      '.......kwwwwwooooooobbbbk...TTT.',
      '.......kooooooooooobbbbBk....T..',
      '......kooooooooooobbbbbBBk...T..',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
  ] },
  splash_small: { w: 8, h: 8, anchor: [4, 4], fps: 16, note: "one-shot, then remove", frames: [
    [
      '........',
      '........',
      '...ww...',
      '..wwwwB.',
      '..BwwwB.',
      '...BB...',
      '........',
      '........',
    ],
    [
      '........',
      '.w....w.',
      '.B.ww.B.',
      '..wwwwB.',
      'w.BwwB.w',
      'B..BB..B',
      '.w....w.',
      '.B....B.',
    ],
    [
      'w......w',
      'B......B',
      '..w..w..',
      '..B..B..',
      '........',
      '.w....w.',
      '.B....B.',
      '........',
    ],
    [
      'b......b',
      '........',
      '........',
      '........',
      '........',
      '........',
      '........',
      'b......b',
    ],
  ] },
  splash_big: { w: 20, h: 16, anchor: [10, 8], fps: 12, note: "one-shot; pair with screen shake", frames: [
    [
      '....................',
      '....................',
      '....................',
      '....................',
      '...w....BBBB........',
      '.......BwwooB...w...',
      '......BwwooobB......',
      '......BoooobbB......',
      '......BoooobbB......',
      '......BoobbbBB......',
      '.......BbbBBB.......',
      '........BBBB........',
      '....w..........w....',
      '....................',
      '....................',
      '....................',
    ],
    [
      '....................',
      '....................',
      '....................',
      '....................',
      '..........ww.ww.....',
      '......wwbbbb.Bn.....',
      '......Bboooob.......',
      '....ww.boooob...ww..',
      '....Bn.boooob...Bn..',
      '....ww.boooob...ww..',
      '....Bn..bbbb....Bn..',
      '..............ww....',
      '.......ww.ww..Bn....',
      '.......Bn.Bn........',
      '....................',
      '....................',
    ],
    [
      '....................',
      '....................',
      '............ww......',
      '.......ww...Bn......',
      '.......Bn.......ww..',
      '...ww...........Bn..',
      '...Bn...............',
      '....................',
      '..ww..............ww',
      '..Bn..............Bn',
      '....................',
      '.................ww.',
      '....ww...........Bn.',
      '....Bn.......ww.....',
      '........ww...Bn.....',
      '........Bn..........',
    ],
    [
      '....................',
      '....................',
      '..........w.........',
      '....w.....B....w....',
      '....B..........B....',
      '....................',
      '.w................w.',
      '.B................B.',
      '....................',
      '....................',
      '..w................w',
      '..B................B',
      '....................',
      '.....w..........w...',
      '.....B....w.....B...',
      '..........B.........',
    ],
    [
      '....................',
      '......b......B......',
      '....................',
      '..................b.',
      '..B.................',
      '....................',
      '....................',
      '....................',
      'b...................',
      '....................',
      '....................',
      '....................',
      '..................b.',
      '..B.................',
      '....................',
      '.......b......B.....',
    ],
  ] },
  puff: { w: 8, h: 6, anchor: [4, 5], fps: 12, note: "one-shot snow dust (footsteps, landings, duck)", frames: [
    [
      '........',
      '........',
      '...ww...',
      '..wwwB..',
      '...BB...',
      '........',
    ],
    [
      '........',
      '..ww....',
      '.wwwwb..',
      '.BwwwbB.',
      '..BBB...',
      '........',
    ],
    [
      '.w...w..',
      '..B.....',
      'w.bb..w.',
      'B..b.B..',
      '...B..b.',
      '........',
    ],
    [
      '.b......',
      '......b.',
      '........',
      'b.......',
      '.....b..',
      '........',
    ],
  ] },
  snowflake: { w: 3, h: 3, anchor: [1, 1], fps: 2, frames: [
    [
      '...',
      '.w.',
      '...',
    ],
    [
      '.w.',
      'wbw',
      '.w.',
    ],
  ] },
  fort_front: { w: 28, h: 12, anchor: [14, 11], note: "outer face (enemy side) with splats", frames: [
    [
      '...nn..nnn...nnn.nn..nnn....',
      '.nnwwnnwwwnnnwwwnwwnnooonnn.',
      'nwwoowwooowwwooowoowooooooon',
      'noobboobbbooobbbobboobbbooon',
      'nbboobbboobbboboboobbboobbbn',
      'noooooobooooooboooooobooooon',
      'nbbbbbwbbbbbbbbbbbbbbbbbbbbn',
      'nooobowwooobooooooboowooobon',
      'nooobooooooboooooobowwwoobon',
      'nbbbbbbbbbbbbbbbbbbbbbbbbbbn',
      '.bBbbbbBbbbbBbbbbBbbbbBbbbb.',
      '.nnnnnnnnnnnnnnnnnnnnnnnnnn.',
    ],
  ] },
  fort_back: { w: 28, h: 12, anchor: [14, 11], note: "inner face with snowball stash", frames: [
    [
      '...nn..nnn...nnn.nn..nnn....',
      '.nnwwnnwwwnnnwwwnwwnnooonnn.',
      'nwwoowwooowwwooowoowooooooon',
      'noobboobbbooobbbobboobbbooon',
      'nbboobbboobbboboboobbboobbbn',
      'noooooobooooooboooooobooooon',
      'nbbbbnnbbbbbbbbbbbbbbbbbbbbn',
      'nooonwonooobooooooboooooobon',
      'nooonobnnooboooooobonnonnbon',
      'nbbnwnnwonbbbbbbbbbnwonwonbn',
      '.bBnobnobnbbBbbbbBbnobnobnb.',
      '.nnnnnnnnnnnnnnnnnnnnnnnnnn.',
    ],
  ] },
  tree_pine: { w: 16, h: 26, anchor: [8, 25], frames: [
    [
      '.......kk.......',
      '.......kk.......',
      '......kgGk......',
      '......kGgk......',
      '.....kggGGk.....',
      '.....kgGgGk.....',
      '....kgggGGGk....',
      '....kggGgGGk....',
      '...kdkdddddkk...',
      '....kgkkkkkkk...',
      '...kggggGGGGk...',
      '...kgggGgGGGk...',
      '...kggggGGGGk...',
      '..kggggGgGGGGk..',
      '..kgggggGGGGGk..',
      '.kdkdkdddddkdkk.',
      '..kgkgkkkkkGkkk.',
      '.kgggggGgGGGGGk.',
      '.kggggggGGGGGGk.',
      '.kgggggGgGGGGGk.',
      'kgggggggGGGGGGGk',
      'dkdkdkdddddkdkdk',
      'k.k.k.kkkkk.k.k.',
      '......ktTk......',
      '......ktTk......',
      '......kkkk......',
    ],
  ] },
  tree_pine_snow: { w: 16, h: 26, anchor: [8, 25], frames: [
    [
      '.......kk.......',
      '.......wo.......',
      '......kwwk......',
      '......kook......',
      '.....kwgbok.....',
      '.....koGgbk.....',
      '....kwggGGok....',
      '....kogGgGGk....',
      '...kwkdddddkk...',
      '....kwkkkkkkk...',
      '...kwowwwoook...',
      '...koggoobGbk...',
      '...kbggbGGGGk...',
      '..kwgggGgGGGok..',
      '..kgggggGGGGbk..',
      '.kwkdkdddddkdkk.',
      '..kwkwkkkkkokkk.',
      '.kwowowwwoobook.',
      '.kogogogobbGbbk.',
      '.kbggggGbGGGGGk.',
      'kwggggggGGGGGGok',
      'wkdkdkdddddkdkbk',
      'k.k.k.kkkkk.k.k.',
      '......ktTk......',
      '......ktTk......',
      '......kkkk......',
    ],
  ] },
  flag_team: { w: 10, h: 18, anchor: [1, 17], fps: 5, note: "uses H/h -> team color; mound of snow at pole base", frames: [
    [
      'kk........',
      'kyk.......',
      'ktHHHHHk..',
      'ktHHHHHHHk',
      'ktHHHHHhk.',
      'kthhhhk...',
      'ktkkk.....',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'kbwk......',
      'kbbk......',
    ],
    [
      'kk........',
      'kyk.......',
      'ktHHHHk...',
      'ktHHHHHHk.',
      'ktHHHHHHhk',
      'kthhhhhk..',
      'ktkkkk....',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'kbwk......',
      'kbbk......',
    ],
    [
      'kk........',
      'kyk.......',
      'ktHHHHHk..',
      'ktHHHHHhk.',
      'ktHHHHhhhk',
      'kthhhkkk..',
      'ktkk......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'kbwk......',
      'kbbk......',
    ],
  ] },
  marker_sign: { w: 24, h: 12, anchor: [0, 4], note: "arrow tip (anchor) = price level. Text: UI.miniFont, max 5 glyphs, top-left at UI.signText.origin (sprite coords), colour UI.signText.color", frames: [
    [
      '...kkkkkkkkkkkkkkkkkkkkk',
      '..kwwwwwbwwwwwwwwwbwwwwk',
      '.kTeeeeeeeeeeeeeeeeeeeTk',
      'kTeeeeeeeeeeeeeeeeeeeeTk',
      'kTeeeeeeeeeeeeeeeeeeeeTk',
      'kTeeeeeeeeeeeeeeeeeeeeTk',
      '.kTeeeeeeeeeeeeeeeeeeeTk',
      '..kTTTTTTTTTTTTTTTTTTTTk',
      '...kkkkkkkkkkkktTkkkkkkk',
      '..............ktTk......',
      '..............ktTk......',
      '.............kbwwbk.....',
    ],
  ] },
  marker_sign_hi: { w: 24, h: 12, anchor: [0, 4], note: "highlighted board for the CURRENT price / round open; same geometry as marker_sign", frames: [
    [
      '...kkkkkkkkkkkkkkkkkkkkk',
      '..kwwwwwbwwwwwwwwwbwwwwk',
      '.kyYYYYYYYYYYYYYYYYYYYyk',
      'kyYYYYYYYYYYYYYYYYYYYYyk',
      'kyYYYYYYYYYYYYYYYYYYYYyk',
      'kyYYYYYYYYYYYYYYYYYYYYyk',
      '.kyYYYYYYYYYYYYYYYYYYYyk',
      '..kyyyyyyyyyyyyyyyyyyyyk',
      '...kkkkkkkkkkkktykkkkkkk',
      '..............ktyk......',
      '..............ktyk......',
      '.............kbwwbk.....',
    ],
  ] },
  snow_tile_a: { w: 16, h: 16, anchor: [0, 0], frames: [
    [
      'oooooooooooooooo',
      'oooooooooooooooo',
      'ooooooooooowoooo',
      'oooooooooooooooo',
      'oooboooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooobooooooo',
      'oooooooooooooooo',
      'oooooooooooobooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'ooooowoooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
    ],
  ] },
  snow_tile_b: { w: 16, h: 16, anchor: [0, 0], frames: [
    [
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooobooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'ooowwwwwwooooooo',
      'oowobbbbbbbbbooo',
      'oooooooooooooboo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'ooooboooowoooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
    ],
  ] },
  snow_tile_c: { w: 16, h: 16, anchor: [0, 0], frames: [
    [
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oowooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooobboooooooo',
      'ooooooooooooowoo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'ooobbooooooooooo',
      'oooooooooobooooo',
      'oooooooooooooooo',
      'ooooooooooooowoo',
      'oooooooooooooooo',
      'oooooooooooooooo',
    ],
  ] },
  border_post: { w: 4, h: 8, anchor: [2, 6], note: "stake along the front line every 32px; rope drawn procedurally between posts", frames: [
    [
      '.kk.',
      'kwwk',
      'ktTk',
      '.tT.',
      '.tT.',
      '.tT.',
      'kbwk',
      '.kk.',
    ],
  ] },
  snow_pile: { w: 12, h: 6, anchor: [6, 5], frames: [
    [
      '....nnnn....',
      '..nnwwwonn..',
      '.nwwwoooobn.',
      'nwwoooooobbn',
      'nbbbbbbbbBBn',
      '.nnnnnnnnnn.',
    ],
  ] },
  ball_stash: { w: 10, h: 7, anchor: [5, 6], note: "pile of ammo; place next to forts", frames: [
    [
      '..nn..nn..',
      '.nwonnwon.',
      '.nobnnobn.',
      '.nnnnnnnn.',
      'nwonwonwon',
      'nobnobnobn',
      '.nn.nn.nn.',
    ],
  ] },
  shadow_kid: { w: 10, h: 3, anchor: [5, 1], note: "draw at kid anchor before the kid", frames: [
    [
      '..bbbbbb..',
      '.bBBBBBBb.',
      '..bbbbbb..',
    ],
  ] },
  shadow_giant: { w: 22, h: 4, anchor: [11, 2], note: "draw at giant anchor before the giant", frames: [
    [
      '.....bbbbbbbbbbbb.....',
      '..bbbBBBBBBBBBBBBbbb..',
      'bbBBBBBBBBBBBBBBBBBBbb',
      '..bbbBBBBBBBBBBBBbbb..',
    ],
  ] },
  icon_head_front: { w: 14, h: 8, anchor: [7, 7], note: "HUD/feed icon: red-team style head (front)", frames: [
    [
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '..khpffffphk..',
      '...kSSSSSSk...',
    ],
  ] },
  icon_head_back: { w: 14, h: 8, anchor: [7, 7], note: "HUD/feed icon: green-team style head (back)", frames: [
    [
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '..kHHhHHhHHk..',
      '..khhhhhhhhk..',
      '..kFttttttFk..',
      '...kSSSSSSk...',
    ],
  ] },
  crown: { w: 11, h: 8, anchor: [5, 7], frames: [
    [
      'k....k....k',
      'kk..kYk..kk',
      'kYk.kyk.kYk',
      'kyYkYyYkYyk',
      'kyyYyyyYyyk',
      'kyjyypyyjyk',
      'kyyyyyyyyyk',
      '.kkkkkkkkk.',
    ],
  ] },
  whale: { w: 13, h: 8, anchor: [6, 7], note: "feed icon for whale events (spout = k dots)", frames: [
    [
      '.........k.k.',
      '..kkkkk...k..',
      '.kjjjjjk.kjk.',
      'kjjwkjjjkjjk.',
      'kjjjjjjjjjk..',
      'kwwwwwJJJk...',
      '.kkwwwJkk....',
      '...kkkk......',
    ],
  ] },
  icon_bolt: { w: 5, h: 8, anchor: [2, 4], note: "feed icon for liquidations", frames: [
    [
      '..kkk',
      '.kYyk',
      '.kYk.',
      'kYYYk',
      'kkYyk',
      '.kYk.',
      '.kk..',
      'k....',
    ],
  ] },
};

export const UI = {
  "fonts": {
    "display": "'Press Start 2P', monospace",
    "body": "'Tiny5', 'Press Start 2P', monospace",
    "css": "https://fonts.googleapis.com/css2?family=Press+Start+2P&family=Tiny5&display=swap"
  },
  "colors": {
    "pageBg": "#10142a",
    "panel": "#1a1c2c",
    "panelAlpha": "rgba(26,28,44,0.88)",
    "panelBorder": "#5d6f9e",
    "panelHighlight": "#8fa7cf",
    "panelShadow": "#0b0d18",
    "text": "#f4f8ff",
    "textDim": "#8fa7cf",
    "up": "#a6e85c",
    "down": "#ff5d6c",
    "green": "#a6e85c",
    "greenDark": "#4fa446",
    "red": "#d63a4f",
    "redDark": "#8a1f3c",
    "neutral": "#bfd2ea",
    "gold": "#ffe27a",
    "goldDark": "#f5b83d",
    "demo": "#f5b83d",
    "live": "#a6e85c",
    "whale": "#7fb8ff",
    "liq": "#ffe27a",
    "signText": "#573522",
    "snow": "#e4eef8",
    "trench": "#5d6f9e",
    "rope": "#dcb784",
    "shakeFlash": "rgba(255,255,255,0.35)"
  },
  "sizes": {
    "price": 16,
    "priceWide": 24,
    "label": 8,
    "body": 16,
    "feed": 16,
    "banner": 14,
    "bannerWide": 24,
    "panelBorder": 2,
    "pressureBarH": 10
  },
  "miniFont": {
    "w": 3,
    "h": 5,
    "advance": 4,
    "glyphs": {
      "0": [
        "###",
        "#.#",
        "#.#",
        "#.#",
        "###"
      ],
      "1": [
        ".#.",
        "##.",
        ".#.",
        ".#.",
        "###"
      ],
      "2": [
        "###",
        "..#",
        "###",
        "#..",
        "###"
      ],
      "3": [
        "###",
        "..#",
        ".##",
        "..#",
        "###"
      ],
      "4": [
        "#.#",
        "#.#",
        "###",
        "..#",
        "..#"
      ],
      "5": [
        "###",
        "#..",
        "###",
        "..#",
        "###"
      ],
      "6": [
        "###",
        "#..",
        "###",
        "#.#",
        "###"
      ],
      "7": [
        "###",
        "..#",
        "..#",
        ".#.",
        ".#."
      ],
      "8": [
        "###",
        "#.#",
        "###",
        "#.#",
        "###"
      ],
      "9": [
        "###",
        "#.#",
        "###",
        "..#",
        "###"
      ],
      ".": [
        "...",
        "...",
        "...",
        "...",
        ".#."
      ],
      ",": [
        "...",
        "...",
        "...",
        ".#.",
        "#.."
      ],
      "-": [
        "...",
        "...",
        "###",
        "...",
        "..."
      ],
      "+": [
        "...",
        ".#.",
        "###",
        ".#.",
        "..."
      ],
      "%": [
        "#.#",
        "..#",
        ".#.",
        "#..",
        "#.#"
      ],
      "$": [
        ".##",
        "##.",
        ".#.",
        ".##",
        "##."
      ],
      "k": [
        "#..",
        "#.#",
        "##.",
        "#.#",
        "#.#"
      ],
      "K": [
        "#.#",
        "#.#",
        "##.",
        "#.#",
        "#.#"
      ],
      " ": [
        "...",
        "...",
        "...",
        "...",
        "..."
      ]
    }
  },
  "signText": {
    "origin": [
      3,
      2
    ],
    "maxChars": 5,
    "color": "#573522"
  }
};
