// Snowball Battle — sprite data. OWNED BY DESIGN (see design/DESIGN.md).
// Format: one char = one pixel. '.' = transparent. H/h/S/s = team colours (swapped by engine).
// Generated from the designer's source; hand edits are fine — keep row length == w, rows == h.

export const PALETTE = {
  ".": null,
  "k": "#1a1c2c",
  "K": "#3b4468",
  "n": "#5d6f9e",
  "B": "#8fa7cf",
  "b": "#bfd2ea",
  "o": "#e4eef8",
  "w": "#ffffff",
  "f": "#f8c9a0",
  "F": "#d99670",
  "p": "#ee8f8f",
  "j": "#4f7ccc",
  "J": "#33539a",
  "y": "#f5b83d",
  "Y": "#ffe27a",
  "t": "#8c5a35",
  "T": "#573522",
  "e": "#dcb784",
  "g": "#3f8a72",
  "G": "#24594f",
  "d": "#163a3a",
  "c": "#f07c34",
  "C": "#b14e1f",
};

// GREEN = high-value lime + bobble beanie with pompom (bottom team, back view).
// RED   = low-value crimson + trapper hat with white fur brim & earflaps (top team, front view).
export const TEAM_COLORS = {
  green: {"H": "#a6e85c", "h": "#4fa446", "S": "#a6e85c", "s": "#4fa446"},
  red: {"H": "#d63a4f", "h": "#8a1f3c", "S": "#d63a4f", "s": "#8a1f3c"},
};

export const TEAM_CHARS = 'HhSs';

export const SPRITES = {
  kid_front_idle: { w: 14, h: 16, anchor: [7, 15], fps: 2, frames: [
    [
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '..khpffffphk..',
      '...kSSSSSSk...',
      '..kjSsjjjjJk..',
      '.kjjSsjjjjJJk.',
      '.kyjsSjjjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..............',
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '..khpffffphk..',
      '...kSSSSSSk...',
      '.kjjSsjjjjJJk.',
      '.kyjsSjjjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_front_windup: { w: 14, h: 16, anchor: [7, 15], fps: 1, note: "hold 180-260 ms, then play throw", frames: [
    [
      '.....kkkk..kk.',
      '....kHHHHkkwwk',
      '...kHHHHHHkwbk',
      '..kwwwwwwwwkyk',
      '..kHffffffHkyk',
      '..kHfkffkfHkjk',
      '..khpffffphkjk',
      '...kSSSSSSk.jk',
      '..kjSsjjjjJJjk',
      '.kjjSsjjjjJk..',
      '.kyjsSjjjjJk..',
      '.kykjjjjjjJk..',
      '..kkKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_front_throw: { w: 14, h: 16, anchor: [7, 15], fps: 10, note: "release on frame 0: ball at anchor + (1,-6) i.e. ground x+1, z=6", frames: [
    [
      '..............',
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '..khpfkkfphk..',
      '...kSSSSSSk...',
      '.kjjSsjkyykJk.',
      '.kyjsSjkyyJJk.',
      '.kykjjjjkkkk..',
      '..kkKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..............',
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '..khpffffphk..',
      '...kSSSSSSk...',
      '.kjjSsjjjjJk..',
      '.kyjsSjjJJJk..',
      '.kykjjjkyyk...',
      '..kkKKKkyyk...',
      '...kKKkkkkk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_front_hit: { w: 14, h: 16, anchor: [7, 15], fps: 8, frames: [
    [
      '..............',
      'B....kkkk.....',
      '....kHHHHk..B.',
      '...kHHHHHHk...',
      '..kwwwwwwwwk.B',
      '..kHwwwwffHk..',
      'B.kHwbwwkfHk..',
      '..khpwwbfphk..',
      '...kSSSSSSk...',
      '..kjSsjjjjJk..',
      '.kjjSsjjjjJJk.',
      '.kyjsSjjjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..B...kkkk....',
      '.....kHHHHk...',
      'B...kHHHHHHk..',
      '...kwwwwwwwwk.',
      '...kHwwwwffHk.',
      '...kHwbwwkfHk.',
      '...khpwwbfphk.',
      '....kSSSSSSk..',
      '...kjSsjjjjJk.',
      '..kjjSsjjjjJJk',
      '..kyjsSjjjjJyk',
      '..kykjjjjjjkyk',
      '...kkKKKKKKkk.',
      '....kKKkkKKk..',
      '...kTTTkkTTTk.',
      '...kkkk..kkkk.',
    ],
  ] },
  kid_front_cheer: { w: 14, h: 16, anchor: [7, 15], fps: 6, frames: [
    [
      '..............',
      '.kk..kkkk..kk.',
      'kyykkHHHHkkyyk',
      'kyykHHHHHHkyyk',
      'kjkwwwwwwwwkjk',
      'kjkHffffffHkjk',
      'kjkHfkffkfHkjk',
      'kjkhpfkkfphkjk',
      '.kjkSSSSSSkjk.',
      '..kjSsjjjjJk..',
      '..kjsSjjjjJk..',
      '..kjjjjjjjJk..',
      '...kKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '.kk..kkkk..kk.',
      'kyykkHHHHkkyyk',
      'kyykHHHHHHkyyk',
      'kjkwwwwwwwwkjk',
      'kjkHffffffHkjk',
      'kjkHfkffkfHkjk',
      'kjkhpfkkfphkjk',
      '.kjkSSSSSSkjk.',
      '..kjSsjjjjJk..',
      '..kjsSjjjjJk..',
      '..kjjjjjjjJk..',
      '...kKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
      '..............',
    ],
  ] },
  kid_front_duck: { w: 14, h: 16, anchor: [7, 15], fps: 2, frames: [
    [
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '.kyhpffffphyk.',
      '.kykSSSSSSkyk.',
      '.kKKjjjjjjKKk.',
      '.kTTkkkkkkTTk.',
    ],
    [
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHkffkffHk..',
      '.kyhpffffphyk.',
      '.kykSSSSSSkyk.',
      '.kKKjjjjjjKKk.',
      '.kTTkkkkkkTTk.',
    ],
  ] },
  kid_back_idle: { w: 14, h: 16, anchor: [7, 15], fps: 2, frames: [
    [
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '..kHHhHHhHHk..',
      '..khhhhhhhhk..',
      '..kFttttttFk..',
      '...kSSSSSSk...',
      '..kjjjSsjjJk..',
      '.kjjjjsSjjJJk.',
      '.kyjjjSsjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..............',
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '..kHHhHHhHHk..',
      '..khhhhhhhhk..',
      '..kFttttttFk..',
      '...kSSSSSSk...',
      '.kjjjjsSjjJJk.',
      '.kyjjjSsjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_back_windup: { w: 14, h: 16, anchor: [7, 15], fps: 1, note: "hold 180-260 ms, then play throw", frames: [
    [
      '......kk...kk.',
      '.....kwwk.kwwk',
      '....kHbbHkkwbk',
      '...kHHHHHHkkyk',
      '..kHHhHHhHHkyk',
      '..khhhhhhhhkjk',
      '..kFttttttFkjk',
      '...kSSSSSSk.jk',
      '..kjjjSsjjJJjk',
      '.kjjjjsSjjJk..',
      '.kyjjjSsjjJk..',
      '.kykjjjjjjJk..',
      '..kkKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_back_throw: { w: 14, h: 16, anchor: [7, 15], fps: 10, note: "release on frame 0: ball at anchor + (5,-13) i.e. ground x+5, z=13", frames: [
    [
      '......kk...kk.',
      '.....kwwk.kyyk',
      '....kHbbHkkyyk',
      '...kHHHHHHkjjk',
      '..kHHhHHhHHkjk',
      '..khhhhhhhhkjk',
      '..kFttttttFkjk',
      '...kSSSSSSkjk.',
      '..kjjjSsjjJjk.',
      '.kjjjjsSjjJk..',
      '.kyjjjSsjjJk..',
      '.kykjjjjjjJk..',
      '..kkKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..............',
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '..kHHhHHhHHk..',
      '..khhhhhhhhk..',
      '..kFttttttFk..',
      '...kSSSSSSk...',
      '..kjjjSsjjJk..',
      '.kjjjjsSjjJJk.',
      '.kyjjjSsjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_back_hit: { w: 14, h: 16, anchor: [7, 15], fps: 8, frames: [
    [
      'B.....kk......',
      '.....kwwk...B.',
      '....kHbbHk....',
      '...kwwwHHHk..B',
      '..kwwbwwhHHk..',
      'B.kwbwwhhhhk..',
      '..kFwwttttFk..',
      '...kSSSSSSk...',
      '..kjjjSsjjJk..',
      '.kjjjjsSjjJJk.',
      '.kyjjjSsjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..B...........',
      'B.....kk......',
      '.....kwwk.....',
      '....kHbbHk...B',
      '...kwwwHHHk...',
      '..kwwbwwhHHk..',
      '..kwbwwhhhhk..',
      '..kFwwttttFk..',
      '...kSSSSSSk...',
      '..kjjjSsjjJk..',
      '.kjjjjsSjjJJk.',
      '.kyjjjSsjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_back_cheer: { w: 14, h: 16, anchor: [7, 15], fps: 6, frames: [
    [
      '..............',
      '.kk...kk...kk.',
      'kyyk.kwwk.kyyk',
      'kyykkHbbHkkyyk',
      'kjkHHHHHHHHkjk',
      'kjkHHhHHhHHkjk',
      'kjkhhhhhhhhkjk',
      'kjkFttttttFkjk',
      '.kjkSSSSSSkjk.',
      '..kjjjSsjjJk..',
      '..kjjjsSjjJk..',
      '..kjjjjjjjJk..',
      '...kKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '.kk...kk...kk.',
      'kyyk.kwwk.kyyk',
      'kyykkHbbHkkyyk',
      'kjkHHHHHHHHkjk',
      'kjkHHhHHhHHkjk',
      'kjkhhhhhhhhkjk',
      'kjkFttttttFkjk',
      '.kjkSSSSSSkjk.',
      '..kjjjSsjjJk..',
      '..kjjjsSjjJk..',
      '..kjjjjjjjJk..',
      '...kKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
      '..............',
    ],
  ] },
  kid_back_duck: { w: 14, h: 16, anchor: [7, 15], fps: 2, frames: [
    [
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '.kyHHhHHhHHyk.',
      '.kyhhhhhhhhyk.',
      'kjkFttttttFkjk',
      'kjjkSSSSSSkjjk',
      '.kjjjjsSjjjJk.',
      '.kTTkkkkkkTTk.',
    ],
    [
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '.......kk.....',
      '......kwwk....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '.kyHHhHHhHHyk.',
      '.kyhhhhhhhhyk.',
      'kjkFttttttFkjk',
      'kjjkSSSSSSkjjk',
      '.kjjjjsSjjjJk.',
      '.kTTkkkkkkTTk.',
    ],
  ] },
  kid_front_beanie_idle: { w: 14, h: 16, anchor: [7, 15], fps: 2, note: "UI/profile only (front view in the GREEN beanie). NEVER on the battlefield.", frames: [
    [
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHhHHhHk...',
      '..khhhhhhhhk..',
      '..kFfkffkfFk..',
      '...kpffffpk...',
      '...kSSSSSSk...',
      '..kjSsjjjjJk..',
      '.kjjSsjjjjJJk.',
      '.kyjsSjjjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..............',
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHhHHhHk...',
      '..khhhhhhhhk..',
      '..kFfkffkfFk..',
      '...kpffffpk...',
      '...kSSSSSSk...',
      '.kjjSsjjjjJJk.',
      '.kyjsSjjjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
  ] },
  kid_front_beanie_cheer: { w: 14, h: 16, anchor: [7, 15], fps: 6, note: "UI/profile only (front view in the GREEN beanie). NEVER on the battlefield.", frames: [
    [
      '..............',
      '.kk...kk...kk.',
      'kyyk.kwwk.kyyk',
      'kyykkHbbHkkyyk',
      'kjkkHhHHhHkkjk',
      'kjkhhhhhhhhkjk',
      'kjkFfkffkfFkjk',
      'kjkkpfkkfpkkjk',
      '.kjkSSSSSSkjk.',
      '..kjSsjjjjJk..',
      '..kjsSjjjjJk..',
      '..kjjjjjjjJk..',
      '...kKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '.kk...kk...kk.',
      'kyyk.kwwk.kyyk',
      'kyykkHbbHkkyyk',
      'kjkkHhHHhHkkjk',
      'kjkhhhhhhhhkjk',
      'kjkFfkffkfFkjk',
      'kjkkpfkkfpkkjk',
      '.kjkSSSSSSkjk.',
      '..kjSsjjjjJk..',
      '..kjsSjjjjJk..',
      '..kjjjjjjjJk..',
      '...kKKKKKKk...',
      '...kKKkkKKk...',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
      '..............',
    ],
  ] },
  kid_front_beanie_hit: { w: 14, h: 16, anchor: [7, 15], fps: 8, note: "UI/profile only (front view in the GREEN beanie). NEVER on the battlefield.", frames: [
    [
      '..............',
      'B.....kk......',
      '.....kwwk...B.',
      '....kHbbHk....',
      '...kHhHHhHk..B',
      '..khhhhhhhhk..',
      'B.kFwwwwkfFk..',
      '...kpwwbfpk...',
      '...kSSSSSSk...',
      '..kjSsjjjjJk..',
      '.kjjSsjjjjJJk.',
      '.kyjsSjjjjJyk.',
      '.kykjjjjjjkyk.',
      '..kkKKKKKKkk..',
      '..kTTTkkTTTk..',
      '..kkkk..kkkk..',
    ],
    [
      '..B....kk.....',
      '......kwwk....',
      'B....kHbbHk...',
      '....kHhHHhHk..',
      '...khhhhhhhhk.',
      '...kFwwwwkfFk.',
      '....kpwwbfpk..',
      '....kSSSSSSk..',
      '...kjSsjjjjJk.',
      '..kjjSsjjjjJJk',
      '..kyjsSjjjjJyk',
      '..kykjjjjjjkyk',
      '...kkKKKKKKkk.',
      '....kKKkkKKk..',
      '...kTTTkkTTTk.',
      '...kkkk..kkkk.',
    ],
  ] },
  ball_small: { w: 4, h: 4, anchor: [2, 2], frames: [
    [
      '.kk.',
      'kwok',
      'kobk',
      '.kk.',
    ],
  ] },
  ball_big: { w: 10, h: 10, anchor: [5, 5], frames: [
    [
      '...kkkk...',
      '.kkwwwokk.',
      '.kwwwoook.',
      'kwwwwooobk',
      'kwwoooobbk',
      'koooooobbk',
      'koooobbbBk',
      '.kobbbbBk.',
      '.kkbbbBkk.',
      '...kkkk...',
    ],
  ] },
  shadow_small: { w: 4, h: 2, anchor: [2, 1], frames: [
    [
      'bBBb',
      '.bb.',
    ],
  ] },
  shadow_big: { w: 10, h: 3, anchor: [5, 1], frames: [
    [
      '..bbbbbb..',
      'bbBBBBBBbb',
      '..bbbbbb..',
    ],
  ] },
  giant_front_idle: { w: 32, h: 40, anchor: [16, 39], fps: 3, frames: [
    [
      '.............kkkkkk.............',
      '...........kkHHHHHHkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHHHHHHHHHhhk.........',
      '........kwwwwwwwwwwwwwbk........',
      '........kwwwwwwwwwwwwbbk........',
      '........kHkkkkkkkkkkkkHk........',
      '........kHkwwwwoooobbkHk........',
      '........khkwwkooookbbkhk........',
      '........khkookooookbbkhk........',
      '.........koooooccccCBBk.........',
      '..........kopoooCCbbpk..........',
      '..TT......kookbbbbbkBk......TT..',
      '..TT......kbbbbkbkBBBk......TT..',
      '.TTT.....k.kkkkkkkkkk..k....TTT.',
      '....t....kssSSssSSssSSsk...t....',
      '.....t...kssSSssSSssSSsk..t.....',
      '......t..kSSkkkkkkkkkkk..t......',
      '.......t.ksSkoooooobbbk.t.......',
      '........kSskoooooobbbBkt........',
      '........ksSkoookkbbbbBt.........',
      '.......kSskooooobbbbBBk.........',
      '.......kSkSooobbbbbBBBk.........',
      '.......k.kkbbbbkkbBBBkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......koooooookkoobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '.............kkkkkk.............',
      '...........kkHHHHHHkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHHHHHHHHHhhk.........',
      '........kwwwwwwwwwwwwwbk........',
      '........kwwwwwwwwwwwwbbk........',
      '........kHkkkkkkkkkkkkHk........',
      '........kHkwwwwoooobbkHk........',
      '........khkwwkooookbbkhk........',
      '........khkookooookbbkhk........',
      '.........koooooccccCBBk.........',
      '..........kopoooCCbbpk..........',
      '..........kookbbbbbkBk..........',
      '..TT......kbbbbkbkBBBk......TT..',
      '..TT.....k.kkkkkkkkkk..k....TT..',
      '.TTT.....kssSSssSSssSSsk....TTT.',
      '....t....kssSSssSSssSSsk...t....',
      '.....tt.kSSkkkkkkkkkkkk..tt.....',
      '.......tksSkwoooooobbbk.t.......',
      '.......kSskooooooobbbBkt........',
      '.......ksSkooookkbbbbBt.........',
      '......kSskoooooobbbbBBk.........',
      '......kSkSoooobbbbbBBBk.........',
      '......k.kkkbbbbkkbBBBkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......koooooookkoobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
  ] },
  giant_front_throw: { w: 32, h: 40, anchor: [16, 39], fps: 6, note: "release frame = 1: spawn ball_big at hand = anchor + (14,-20) (ground x+14, height z=20)", frames: [
    [
      '.............kkkkkk.....kkkk....',
      '...........kkHHHHHHkk.kkwwwokk..',
      '..........kHHHHHHHHHHkkwwwoook..',
      '.........kHHHHHHHHHHHhkwwwooobk.',
      '.........kHHHHHHHHHHhhkwoooobbk.',
      '........kwwwwwwwwwwwwwbkoooobbk.',
      '........kwwwwwwwwwwwwbbkoobbbBk.',
      '........kHkkkkkkkkkkkkHkbbbbBk..',
      '........kHkwwwwoooobbkHkbTbTkk..',
      '........khkwwkooookbbkhkkkTk....',
      '........khkookooookbbkhk..t.....',
      '.........koooooccccCBBk..t......',
      '..........kopoooCCbbpk...t......',
      '..........kookbbbbbkBk...t......',
      '..TT......kbbbbkbkBBBk..t.......',
      '..TT.....k.kkkkkkkkkk..kt.......',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kSSkkkkkkkkkkkt........',
      '.......t.ksSkoooooobbbt.........',
      '........kSskoooooobbbBt.........',
      '........ksSkoookkbbbbBk.........',
      '.......kSskooooobbbbBBk.........',
      '.......kSkSooobbbbbBBBk.........',
      '.......k.kkbbbbkkbBBBkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......koooooookkoobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '.............kkkkkk.............',
      '...........kkHHHHHHkk...........',
      '..........kHHHHHHHHHHk.....B....',
      '.........kHHHHHHHHHHHhk.....b...',
      '.........kHHHHHHHHHHhhk......B..',
      '........kwwwwwwwwwwwwwbk.....B..',
      '........kwwwwwwwwwwwwbbk......b.',
      '........kHkkkkkkkkkkkkHk......B.',
      '........kHkwwwwoooobbkHk.......B',
      '........khkwwkooookbbkhk.......b',
      '........khkookooookbbkhk.......B',
      '.........koooooccccCBBk........B',
      '..........kopoooCCbbpk.........b',
      '..........kookbbbbbkBk........B.',
      '..TT......kbbbbkbkBBBk........B.',
      '..TT.....k.kkkkkkkkkk..k........',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kSSkkkkkkkkkkk........T',
      '.......t.ksSkoooooobbbk...ttttT.',
      '........kSskoooooobbbBtttt.....T',
      '........ksSkoookkbbbbBk.........',
      '.......kSskooooobbbbBBk.........',
      '.......kSkSooobbbbbBBBk.........',
      '.......k.kkbbbbkkbBBBkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......koooooookkoobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '.............kkkkkk.............',
      '...........kkHHHHHHkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHHHHHHHHHhhk.........',
      '........kwwwwwwwwwwwwwbk........',
      '........kwwwwwwwwwwwwbbk........',
      '........kHkkkkkkkkkkkkHk........',
      '........kHkwwwwoooobbkHk........',
      '........khkwwkooookbbkhk........',
      '........khkookooookbbkhk........',
      '.........koooooccccCBBk.........',
      '..........kopoooCCbbpk..........',
      '..........kookbbbbbkBk..........',
      '..TT......kbbbbkbkBBBk..........',
      '..TT.....k.kkkkkkkkkk..k........',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kSSkkkkkkkkkkk.........',
      '.......t.ksSkoooooobbbk.........',
      '........kSskoooooobbbBk.........',
      '........ksSkoookkbbbbBk.........',
      '.......kSskooooobbbbBBt.........',
      '.......kSkSooobbbbbBBBkt........',
      '.......k.kkbbbbkkbBBBkk.t.......',
      '........kwkbbbbbBBBBBkbk.t......',
      '.......kwwwkkBBBBBBkkbbbk.t.....',
      '.......kwwwwwkkkkkkoobbbk..t....',
      '.......kwwwwwooooooobbbbk...TTT.',
      '.......koooooookkoobbbbBk....T..',
      '......kooooooooooobbbbbBBk...T..',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
  ] },
  giant_back_idle: { w: 32, h: 40, anchor: [16, 39], fps: 3, frames: [
    [
      '..............kkkk..............',
      '.............kwwwwk.............',
      '.............kwwwbk.............',
      '...........kkkbbbbkkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '........khhhhhhhhhhhhhhk........',
      '........khhhhhhhhhhhhhhk........',
      '.........kkkkkkkkkkkkkk.........',
      '.........kooooooobbbBBk.........',
      '..........kooooobbbbBk..........',
      '..TT......kooobbbbbBBk......TT..',
      '..TT......kbbbbbbBBBBk......TT..',
      '.TTT.....k.kkkkkkkkkk..k....TTT.',
      '....t....kssSSssSSssSSsk...t....',
      '.....t...kssSSssSSssSSsk..t.....',
      '......t..kkkkkkkkkSSkkk..t......',
      '.......t.kwwwooooksSkbk.t.......',
      '........tkoooooookSskBkt........',
      '.........tooooooobksSkt.........',
      '.........koooooobbkSskk.........',
      '.........koooobbbbkSkSk.........',
      '.........kkbbbbbbbBBkkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......kooooooooooobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '..............kkkk..............',
      '.............kwwwwk.............',
      '.............kwwwbk.............',
      '...........kkkbbbbkkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '........khhhhhhhhhhhhhhk........',
      '........khhhhhhhhhhhhhhk........',
      '.........kkkkkkkkkkkkkk.........',
      '.........kooooooobbbBBk.........',
      '..........kooooobbbbBk..........',
      '..........kooobbbbbBBk..........',
      '..TT......kbbbbbbBBBBk......TT..',
      '..TT.....k.kkkkkkkkkk..k....TT..',
      '.TTT.....kssSSssSSssSSsk....TTT.',
      '....t....kssSSssSSssSSsk...t....',
      '.....tt..kkkkkkkkkkSSkk..tt.....',
      '.......t.kwwwoooooksSkk.t.......',
      '........tkooooooookSskkt........',
      '.........tooooooobbksSk.........',
      '.........koooooobbbkSsk.........',
      '.........koooobbbbbkSkS.........',
      '.........kkbbbbbbbBBBkkk........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......kooooooooooobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
  ] },
  giant_back_throw: { w: 32, h: 40, anchor: [16, 39], fps: 6, note: "release frame = 1: spawn ball_big at hand = anchor + (14,-20) (ground x+14, height z=20)", frames: [
    [
      '..............kkkk......kkkk....',
      '.............kwwwwk...kkwwwokk..',
      '.............kwwwbk...kwwwoook..',
      '...........kkkbbbbkkkkwwwwooobk.',
      '..........kHHHHHHHHHHkwwoooobbk.',
      '.........kHHHHHHHHHHHhkooooobbk.',
      '.........kHHhHHhHHhHhhkooobbbBk.',
      '.........kHHhHHhHHhHhhkobbbbBk..',
      '........khhhhhhhhhhhhhhkbTbTkk..',
      '........khhhhhhhhhhhhhhkkkTk....',
      '.........kkkkkkkkkkkkkk...t.....',
      '.........kooooooobbbBBk..t......',
      '..........kooooobbbbBk...t......',
      '..........kooobbbbbBBk...t......',
      '..TT......kbbbbbbBBBBk..t.......',
      '..TT.....k.kkkkkkkkkk..kt.......',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kkkkkkkkkSSkkkt........',
      '.......t.kwwwooooksSkbt.........',
      '........tkoooooookSskBt.........',
      '.........tooooooobksSkk.........',
      '.........koooooobbkSskk.........',
      '.........koooobbbbkSkSk.........',
      '.........kkbbbbbbbBBkkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......kooooooooooobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '..............kkkk..............',
      '.............kwwwwk.............',
      '.............kwwwbk........B....',
      '...........kkkbbbbkkk.......b...',
      '..........kHHHHHHHHHHk.......B..',
      '.........kHHHHHHHHHHHhk......B..',
      '.........kHHhHHhHHhHhhk.......b.',
      '.........kHHhHHhHHhHhhk.......B.',
      '........khhhhhhhhhhhhhhk.......B',
      '........khhhhhhhhhhhhhhk.......b',
      '.........kkkkkkkkkkkkkk........B',
      '.........kooooooobbbBBk........B',
      '..........kooooobbbbBk.........b',
      '..........kooobbbbbBBk........B.',
      '..TT......kbbbbbbBBBBk........B.',
      '..TT.....k.kkkkkkkkkk..k........',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kkkkkkkkkSSkkk........T',
      '.......t.kwwwooooksSkbk...ttttT.',
      '........tkoooooookSskBtttt.....T',
      '.........tooooooobksSkk.........',
      '.........koooooobbkSskk.........',
      '.........koooobbbbkSkSk.........',
      '.........kkbbbbbbbBBkkk.........',
      '........kwkbbbbbBBBBBkbk........',
      '.......kwwwkkBBBBBBkkbbbk.......',
      '.......kwwwwwkkkkkkoobbbk.......',
      '.......kwwwwwooooooobbbbk.......',
      '.......kooooooooooobbbbBk.......',
      '......kooooooooooobbbbbBBk......',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
    [
      '..............kkkk..............',
      '.............kwwwwk.............',
      '.............kwwwbk.............',
      '...........kkkbbbbkkk...........',
      '..........kHHHHHHHHHHk..........',
      '.........kHHHHHHHHHHHhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '.........kHHhHHhHHhHhhk.........',
      '........khhhhhhhhhhhhhhk........',
      '........khhhhhhhhhhhhhhk........',
      '.........kkkkkkkkkkkkkk.........',
      '.........kooooooobbbBBk.........',
      '..........kooooobbbbBk..........',
      '..........kooobbbbbBBk..........',
      '..TT......kbbbbbbBBBBk..........',
      '..TT.....k.kkkkkkkkkk..k........',
      '.TTT.....kssSSssSSssSSsk........',
      '....t....kssSSssSSssSSsk........',
      '.....tt..kkkkkkkkkSSkkk.........',
      '.......t.kwwwooooksSkbk.........',
      '........tkoooooookSskBk.........',
      '.........tooooooobksSkk.........',
      '.........koooooobbkSskt.........',
      '.........koooobbbbkSkSkt........',
      '.........kkbbbbbbbBBkkk.t.......',
      '........kwkbbbbbBBBBBkbk.t......',
      '.......kwwwkkBBBBBBkkbbbk.t.....',
      '.......kwwwwwkkkkkkoobbbk..t....',
      '.......kwwwwwooooooobbbbk...TTT.',
      '.......kooooooooooobbbbBk....T..',
      '......kooooooooooobbbbbBBk...T..',
      '.......kooooooooobbbbbBBk.......',
      '.......koooooooobbbbbbBBk.......',
      '.......koooooobbbbbbbBBBk.......',
      '.......kbbbbbbbbbbbbBBBBk.......',
      '........kbbbbbbbbbBBBBBk........',
      '.........kbbbbbbBBBBBBk.........',
      '..........kbbBBBBBBBBk..........',
      '...........kkBBBBBBkk...........',
      '.............kkkkkk.............',
    ],
  ] },
  splash_small: { w: 8, h: 8, anchor: [4, 4], fps: 16, note: "one-shot, then remove", frames: [
    [
      '........',
      '........',
      '...ww...',
      '..wwwwB.',
      '..BwwwB.',
      '...BB...',
      '........',
      '........',
    ],
    [
      '........',
      '.w....w.',
      '.B.ww.B.',
      '..wwwwB.',
      'w.BwwB.w',
      'B..BB..B',
      '.w....w.',
      '.B....B.',
    ],
    [
      'w......w',
      'B......B',
      '..w..w..',
      '..B..B..',
      '........',
      '.w....w.',
      '.B....B.',
      '........',
    ],
    [
      'b......b',
      '........',
      '........',
      '........',
      '........',
      '........',
      '........',
      'b......b',
    ],
  ] },
  splash_big: { w: 20, h: 16, anchor: [10, 8], fps: 12, note: "one-shot; pair with screen shake", frames: [
    [
      '....................',
      '....................',
      '....................',
      '....................',
      '...w....BBBB........',
      '.......BwwooB...w...',
      '......BwwooobB......',
      '......BoooobbB......',
      '......BoooobbB......',
      '......BoobbbBB......',
      '.......BbbBBB.......',
      '........BBBB........',
      '....w..........w....',
      '....................',
      '....................',
      '....................',
    ],
    [
      '....................',
      '....................',
      '....................',
      '....................',
      '..........ww.ww.....',
      '......wwbbbb.Bn.....',
      '......Bboooob.......',
      '....ww.boooob...ww..',
      '....Bn.boooob...Bn..',
      '....ww.boooob...ww..',
      '....Bn..bbbb....Bn..',
      '..............ww....',
      '.......ww.ww..Bn....',
      '.......Bn.Bn........',
      '....................',
      '....................',
    ],
    [
      '....................',
      '....................',
      '............ww......',
      '.......ww...Bn......',
      '.......Bn.......ww..',
      '...ww...........Bn..',
      '...Bn...............',
      '....................',
      '..ww..............ww',
      '..Bn..............Bn',
      '....................',
      '.................ww.',
      '....ww...........Bn.',
      '....Bn.......ww.....',
      '........ww...Bn.....',
      '........Bn..........',
    ],
    [
      '....................',
      '....................',
      '..........w.........',
      '....w.....B....w....',
      '....B..........B....',
      '....................',
      '.w................w.',
      '.B................B.',
      '....................',
      '....................',
      '..w................w',
      '..B................B',
      '....................',
      '.....w..........w...',
      '.....B....w.....B...',
      '..........B.........',
    ],
    [
      '....................',
      '......b......B......',
      '....................',
      '..................b.',
      '..B.................',
      '....................',
      '....................',
      '....................',
      'b...................',
      '....................',
      '....................',
      '....................',
      '..................b.',
      '..B.................',
      '....................',
      '.......b......B.....',
    ],
  ] },
  puff: { w: 8, h: 6, anchor: [4, 5], fps: 12, note: "one-shot snow dust (footsteps, landings, duck)", frames: [
    [
      '........',
      '........',
      '...ww...',
      '..wwwB..',
      '...BB...',
      '........',
    ],
    [
      '........',
      '..ww....',
      '.wwwwb..',
      '.BwwwbB.',
      '..BBB...',
      '........',
    ],
    [
      '.w...w..',
      '..B.....',
      'w.bb..w.',
      'B..b.B..',
      '...B..b.',
      '........',
    ],
    [
      '.b......',
      '......b.',
      '........',
      'b.......',
      '.....b..',
      '........',
    ],
  ] },
  snowflake: { w: 3, h: 3, anchor: [1, 1], fps: 2, frames: [
    [
      '...',
      '.w.',
      '...',
    ],
    [
      '.w.',
      'wbw',
      '.w.',
    ],
  ] },
  fort_front: { w: 28, h: 12, anchor: [14, 11], note: "outer face (enemy side) with splats", frames: [
    [
      '...nn..nnn...nnn.nn..nnn....',
      '.nnwwnnwwwnnnwwwnwwnnooonnn.',
      'nwwoowwooowwwooowoowooooooon',
      'noobboobbbooobbbobboobbbooon',
      'nbboobbboobbboboboobbboobbbn',
      'noooooobooooooboooooobooooon',
      'nbbbbbwbbbbbbbbbbbbbbbbbbbbn',
      'nooobowwooobooooooboowooobon',
      'nooobooooooboooooobowwwoobon',
      'nbbbbbbbbbbbbbbbbbbbbbbbbbbn',
      '.bBbbbbBbbbbBbbbbBbbbbBbbbb.',
      '.nnnnnnnnnnnnnnnnnnnnnnnnnn.',
    ],
  ] },
  fort_back: { w: 28, h: 12, anchor: [14, 11], note: "inner face with snowball stash", frames: [
    [
      '...nn..nnn...nnn.nn..nnn....',
      '.nnwwnnwwwnnnwwwnwwnnooonnn.',
      'nwwoowwooowwwooowoowooooooon',
      'noobboobbbooobbbobboobbbooon',
      'nbboobbboobbboboboobbboobbbn',
      'noooooobooooooboooooobooooon',
      'nbbbbnnbbbbbbbbbbbbbbbbbbbbn',
      'nooonwonooobooooooboooooobon',
      'nooonobnnooboooooobonnonnbon',
      'nbbnwnnwonbbbbbbbbbnwonwonbn',
      '.bBnobnobnbbBbbbbBbnobnobnb.',
      '.nnnnnnnnnnnnnnnnnnnnnnnnnn.',
    ],
  ] },
  tree_pine: { w: 16, h: 26, anchor: [8, 25], frames: [
    [
      '.......kk.......',
      '.......kk.......',
      '......kgGk......',
      '......kGgk......',
      '.....kggGGk.....',
      '.....kgGgGk.....',
      '....kgggGGGk....',
      '....kggGgGGk....',
      '...kdkdddddkk...',
      '....kgkkkkkkk...',
      '...kggggGGGGk...',
      '...kgggGgGGGk...',
      '...kggggGGGGk...',
      '..kggggGgGGGGk..',
      '..kgggggGGGGGk..',
      '.kdkdkdddddkdkk.',
      '..kgkgkkkkkGkkk.',
      '.kgggggGgGGGGGk.',
      '.kggggggGGGGGGk.',
      '.kgggggGgGGGGGk.',
      'kgggggggGGGGGGGk',
      'dkdkdkdddddkdkdk',
      'k.k.k.kkkkk.k.k.',
      '......ktTk......',
      '......ktTk......',
      '......kkkk......',
    ],
  ] },
  tree_pine_snow: { w: 16, h: 26, anchor: [8, 25], frames: [
    [
      '.......kk.......',
      '.......wo.......',
      '......kwwk......',
      '......kook......',
      '.....kwgbok.....',
      '.....koGgbk.....',
      '....kwggGGok....',
      '....kogGgGGk....',
      '...kwkdddddkk...',
      '....kwkkkkkkk...',
      '...kwowwwoook...',
      '...koggoobGbk...',
      '...kbggbGGGGk...',
      '..kwgggGgGGGok..',
      '..kgggggGGGGbk..',
      '.kwkdkdddddkdkk.',
      '..kwkwkkkkkokkk.',
      '.kwowowwwoobook.',
      '.kogogogobbGbbk.',
      '.kbggggGbGGGGGk.',
      'kwggggggGGGGGGok',
      'wkdkdkdddddkdkbk',
      'k.k.k.kkkkk.k.k.',
      '......ktTk......',
      '......ktTk......',
      '......kkkk......',
    ],
  ] },
  flag_team: { w: 10, h: 18, anchor: [1, 17], fps: 5, note: "uses H/h -> team color; mound of snow at pole base", frames: [
    [
      'kk........',
      'kyk.......',
      'ktHHHHHk..',
      'ktHHHHHHHk',
      'ktHHHHHhk.',
      'kthhhhk...',
      'ktkkk.....',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'kbwk......',
      'kbbk......',
    ],
    [
      'kk........',
      'kyk.......',
      'ktHHHHk...',
      'ktHHHHHHk.',
      'ktHHHHHHhk',
      'kthhhhhk..',
      'ktkkkk....',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'kbwk......',
      'kbbk......',
    ],
    [
      'kk........',
      'kyk.......',
      'ktHHHHHk..',
      'ktHHHHHhk.',
      'ktHHHHhhhk',
      'kthhhkkk..',
      'ktkk......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'ktk.......',
      'kbwk......',
      'kbbk......',
    ],
  ] },
  marker_sign: { w: 24, h: 12, anchor: [0, 4], note: "arrow tip (anchor) = price level. Text: UI.miniFont, max 5 glyphs, top-left at UI.signText.origin (sprite coords), colour UI.signText.color", frames: [
    [
      '...kkkkkkkkkkkkkkkkkkkkk',
      '..kwwwwwbwwwwwwwwwbwwwwk',
      '.kTeeeeeeeeeeeeeeeeeeeTk',
      'kTeeeeeeeeeeeeeeeeeeeeTk',
      'kTeeeeeeeeeeeeeeeeeeeeTk',
      'kTeeeeeeeeeeeeeeeeeeeeTk',
      '.kTeeeeeeeeeeeeeeeeeeeTk',
      '..kTTTTTTTTTTTTTTTTTTTTk',
      '...kkkkkkkkkkkktTkkkkkkk',
      '..............ktTk......',
      '..............ktTk......',
      '.............kbwwbk.....',
    ],
  ] },
  marker_sign_hi: { w: 24, h: 12, anchor: [0, 4], note: "highlighted board for the CURRENT price / round open; same geometry as marker_sign", frames: [
    [
      '...kkkkkkkkkkkkkkkkkkkkk',
      '..kwwwwwbwwwwwwwwwbwwwwk',
      '.kyYYYYYYYYYYYYYYYYYYYyk',
      'kyYYYYYYYYYYYYYYYYYYYYyk',
      'kyYYYYYYYYYYYYYYYYYYYYyk',
      'kyYYYYYYYYYYYYYYYYYYYYyk',
      '.kyYYYYYYYYYYYYYYYYYYYyk',
      '..kyyyyyyyyyyyyyyyyyyyyk',
      '...kkkkkkkkkkkktykkkkkkk',
      '..............ktyk......',
      '..............ktyk......',
      '.............kbwwbk.....',
    ],
  ] },
  snow_tile_a: { w: 16, h: 16, anchor: [0, 0], frames: [
    [
      'oooooooooooooooo',
      'oooooooooooooooo',
      'ooooooooooowoooo',
      'oooooooooooooooo',
      'oooboooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooobooooooo',
      'oooooooooooooooo',
      'oooooooooooobooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'ooooowoooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
    ],
  ] },
  snow_tile_b: { w: 16, h: 16, anchor: [0, 0], frames: [
    [
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooobooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'ooowwwwwwooooooo',
      'oowobbbbbbbbbooo',
      'oooooooooooooboo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'ooooboooowoooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
    ],
  ] },
  snow_tile_c: { w: 16, h: 16, anchor: [0, 0], frames: [
    [
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oowooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooobboooooooo',
      'ooooooooooooowoo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'oooooooooooooooo',
      'ooobbooooooooooo',
      'oooooooooobooooo',
      'oooooooooooooooo',
      'ooooooooooooowoo',
      'oooooooooooooooo',
      'oooooooooooooooo',
    ],
  ] },
  border_post: { w: 4, h: 8, anchor: [2, 6], note: "stake along the front line every 32px; rope drawn procedurally between posts", frames: [
    [
      '.kk.',
      'kwwk',
      'ktTk',
      '.tT.',
      '.tT.',
      '.tT.',
      'kbwk',
      '.kk.',
    ],
  ] },
  snow_pile: { w: 12, h: 6, anchor: [6, 5], frames: [
    [
      '....nnnn....',
      '..nnwwwonn..',
      '.nwwwoooobn.',
      'nwwoooooobbn',
      'nbbbbbbbbBBn',
      '.nnnnnnnnnn.',
    ],
  ] },
  ball_stash: { w: 10, h: 7, anchor: [5, 6], note: "pile of ammo; place next to forts", frames: [
    [
      '..nn..nn..',
      '.nwonnwon.',
      '.nobnnobn.',
      '.nnnnnnnn.',
      'nwonwonwon',
      'nobnobnobn',
      '.nn.nn.nn.',
    ],
  ] },
  shadow_kid: { w: 10, h: 3, anchor: [5, 1], note: "draw at kid anchor before the kid", frames: [
    [
      '..bbbbbb..',
      '.bBBBBBBb.',
      '..bbbbbb..',
    ],
  ] },
  shadow_giant: { w: 22, h: 4, anchor: [11, 2], note: "draw at giant anchor before the giant", frames: [
    [
      '.....bbbbbbbbbbbb.....',
      '..bbbBBBBBBBBBBBBbbb..',
      'bbBBBBBBBBBBBBBBBBBBbb',
      '..bbbBBBBBBBBBBBBbbb..',
    ],
  ] },
  icon_head_front: { w: 14, h: 8, anchor: [7, 7], note: "HUD/feed icon: red-team style head (front)", frames: [
    [
      '.....kkkk.....',
      '....kHHHHk....',
      '...kHHHHHHk...',
      '..kwwwwwwwwk..',
      '..kHffffffHk..',
      '..kHfkffkfHk..',
      '..khpffffphk..',
      '...kSSSSSSk...',
    ],
  ] },
  icon_head_back: { w: 14, h: 8, anchor: [7, 7], note: "HUD/feed icon: green-team style head (back)", frames: [
    [
      '......kk......',
      '.....kwwk.....',
      '....kHbbHk....',
      '...kHHHHHHk...',
      '..kHHhHHhHHk..',
      '..khhhhhhhhk..',
      '..kFttttttFk..',
      '...kSSSSSSk...',
    ],
  ] },
  crown: { w: 11, h: 8, anchor: [5, 7], frames: [
    [
      'k....k....k',
      'kk..kYk..kk',
      'kYk.kyk.kYk',
      'kyYkYyYkYyk',
      'kyyYyyyYyyk',
      'kyjyypyyjyk',
      'kyyyyyyyyyk',
      '.kkkkkkkkk.',
    ],
  ] },
  whale: { w: 13, h: 8, anchor: [6, 7], note: "feed icon for whale events (spout = k dots)", frames: [
    [
      '.........k.k.',
      '..kkkkk...k..',
      '.kjjjjjk.kjk.',
      'kjjwkjjjkjjk.',
      'kjjjjjjjjjk..',
      'kwwwwwJJJk...',
      '.kkwwwJkk....',
      '...kkkk......',
    ],
  ] },
  icon_bolt: { w: 5, h: 8, anchor: [2, 4], note: "feed icon for liquidations", frames: [
    [
      '..kkk',
      '.kYyk',
      '.kYk.',
      'kYYYk',
      'kkYyk',
      '.kYk.',
      '.kk..',
      'k....',
    ],
  ] },
  ach_target: { w: 10, h: 10, anchor: [5, 5], note: "achievement icon 10x10; draw at 2x on HUD; locked = see DESIGN.md §10", frames: [
    [
      '...kkkk...',
      '..kcccck..',
      '.kcwwwwck.',
      'kcwwccwwck',
      'kcwcYYcwck',
      'kcwcYYcwck',
      'kcwwccwwck',
      '.kCwwwwCk.',
      '..kCCCCk..',
      '...kkkk...',
    ],
  ] },
  ach_carrot: { w: 10, h: 10, anchor: [5, 5], note: "achievement icon 10x10; draw at 2x on HUD; locked = see DESIGN.md §10", frames: [
    [
      '......k.k.',
      '.....kgkgk',
      '.....kgGgk',
      '....kccGgk',
      '...kcccCk.',
      '..kcYccCk.',
      '..kccCCk..',
      '.kccCkk...',
      'kcCkk.....',
      '.kk.......',
    ],
  ] },
  ach_flame: { w: 10, h: 10, anchor: [5, 5], note: "achievement icon 10x10; draw at 2x on HUD; locked = see DESIGN.md §10", frames: [
    [
      '....k.....',
      '...kck..k.',
      '...kcckkck',
      '..kcyckcck',
      '.kccyycyck',
      'kcyyYyyyck',
      'kcyYYwYyck',
      'kcyYwwYyck',
      '.kCyyyyCk.',
      '..kkkkkk..',
    ],
  ] },
  ach_iceball: { w: 10, h: 10, anchor: [5, 5], note: "achievement icon 10x10; draw at 2x on HUD; locked = see DESIGN.md §10", frames: [
    [
      '...kkkk...',
      '..kwwbbk..',
      '.kwwbbbbk.',
      '.kwbbwbBk.',
      '.kbbwwwBk.',
      '.kbbBwBjk.',
      '..kBBjjk..',
      '.kJJJJJJk.',
      'kKKKKKKKKk',
      '.kkkkkkkk.',
    ],
  ] },
  ach_bullfinch: { w: 10, h: 10, anchor: [5, 5], note: "achievement icon 10x10; draw at 2x on HUD; locked = see DESIGN.md §10", frames: [
    [
      '....kkk...',
      '...knnnk..',
      '.kknKKKBk.',
      'kKKKwKBBBk',
      '.kkpppBBBk',
      '.kppppwwKk',
      '.kppppBBKk',
      '.kkppBBKk.',
      'kttttttttk',
      '.kkkkkkkk.',
    ],
  ] },
  ach_calendar: { w: 10, h: 10, anchor: [5, 5], note: "achievement icon 10x10; draw at 2x on HUD; locked = see DESIGN.md §10", frames: [
    [
      '.kkkkkkkk.',
      'kcKccccKck',
      'kcccccccck',
      'kwwwwwwwwk',
      'kwwkkkkwwk',
      'kwwwwwkwwk',
      'kwwwwkwwwk',
      'kwwwkwwwwk',
      'kbbbkbbbbk',
      '.kkk.kkkk.',
    ],
  ] },
  ach_icicle: { w: 10, h: 10, anchor: [5, 5], note: "achievement icon 10x10; draw at 2x on HUD; locked = see DESIGN.md §10", frames: [
    [
      '.kkkkkkkk.',
      'kwwwwwwwwk',
      'kbbBbbbBbk',
      'kwBkwbBkwk',
      'kwBkwbBkbk',
      '.kbkwbBkbk',
      '..kkwBkkjk',
      '...kwBk.k.',
      '....kjk...',
      '.....k....',
    ],
  ] },
  cos_pin_star: { w: 3, h: 3, anchor: [1, 1], note: "hat badge; draw at HAT_POINTS[..][f].pin", frames: [
    [
      '.y.',
      'yYy',
      'y.y',
    ],
  ] },
  cos_pin_whale: { w: 4, h: 3, anchor: [2, 1], note: "hat badge (4 wide: centred on the head); draw at pin", frames: [
    [
      'w..j',
      'jjjj',
      '.JJ.',
    ],
  ] },
  cos_pin_cockade: { w: 3, h: 3, anchor: [1, 1], note: "hat badge; draw at pin", frames: [
    [
      '.y.',
      'yjy',
      '.y.',
    ],
  ] },
  cos_crown_top: { w: 8, h: 4, anchor: [4, 3], note: "crown on top of hat/pompom; anchor = bottom centre, draw at HAT_POINTS[..][f].top", frames: [
    [
      'y..yy..y',
      'yy.yy.yy',
      'yYyYYyYy',
      'kkkkkkkk',
    ],
  ] },
  cos_snow_front: { w: 8, h: 5, anchor: [4, 1], note: "white dots on the trapper H (front view); draw at pin", frames: [
    [
      '..w.....',
      '......w.',
      '........',
      'w.......',
      '.......w',
    ],
  ] },
  cos_snow_beanie: { w: 6, h: 2, anchor: [3, 1], note: "white dots on the beanie H seen from the FRONT (kid_front_beanie_*); draw at pin", frames: [
    [
      '.w....',
      'w....w',
    ],
  ] },
  cos_snow_back: { w: 7, h: 3, anchor: [3, 2], note: "white dots on the beanie H (back view); draw at pin", frames: [
    [
      '....w..',
      'w......',
      '......w',
    ],
  ] },
  marker_you: { w: 5, h: 4, anchor: [2, 3], note: "owner marker; draw at (top.x, top.y - 2), or above the crown (top.y - 5) when a crown is worn", frames: [
    [
      'kkkkk',
      'kYYyk',
      '.kyk.',
      '..k..',
    ],
  ] },
  pet_penguin_idle: { w: 10, h: 10, anchor: [5, 8], fps: 2, note: "companion pet (owner only)", frames: [
    [
      '...kkkk...',
      '..kKKKKk..',
      '.kKwwwwKk.',
      '.kKkwwkKk.',
      '.kKwyywKk.',
      '..kKwwKk..',
      '.kKKwwKKk.',
      '.kKwwwwKk.',
      '..kykkyk..',
      '...k..k...',
    ],
    [
      '...kkkk...',
      '..kKKKKk..',
      '.kKwwwwKk.',
      '.kKkwwkKk.',
      '.kKwyywKk.',
      '.kkKwwKkk.',
      'kKKKwwKKKk',
      '.kKwwwwKk.',
      '..kykkyk..',
      '...k..k...',
    ],
  ] },
  pet_penguin_hop: { w: 10, h: 10, anchor: [5, 8], note: "hop pose; engine lifts it by PETS.hop.px", frames: [
    [
      '...kkkk...',
      '..kKKKKk..',
      '.kKwwwwKk.',
      '.kKkwwkKk.',
      '.kKwyywKk.',
      '.kkKwwKkk.',
      'kKKKwwKKKk',
      '.kKwwwwKk.',
      '..kkyykk..',
      '....kk....',
    ],
  ] },
  pet_bullfinch_idle: { w: 10, h: 8, anchor: [5, 6], fps: 2, note: "companion pet (owner only)", frames: [
    [
      '...kkk....',
      '..kKKKk...',
      '.kKKwKBk..',
      'kKKKKBBBk.',
      '.kppppwBKk',
      '.kpppBBKKk',
      '..kKkkKkk.',
      '...k..k...',
    ],
    [
      '..........',
      '...kkk....',
      '..kKKKk.k.',
      '.kKKwKBkKk',
      'kKKKKBBBKk',
      '.kppppwBk.',
      '..kKkkKk..',
      '...k..k...',
    ],
  ] },
  pet_bullfinch_hop: { w: 10, h: 8, anchor: [5, 6], note: "hop pose; engine lifts it by PETS.hop.px", frames: [
    [
      '...kkk....',
      '..kKKKkkk.',
      '.kKKwKBwwk',
      'kKKKKBwwBk',
      '.kppppBBKk',
      '.kpppBBKKk',
      '..kkKKkkk.',
      '....kk....',
    ],
  ] },
  pet_fox_idle: { w: 12, h: 7, anchor: [6, 5], fps: 2, note: "companion pet (owner only)", frames: [
    [
      '..k.k.......',
      '.kbkbk...kk.',
      '.kwwwwkkkbbk',
      'kKwkwwwwwbwk',
      '.kwwwwwwwwk.',
      '.kbbkkbbkk..',
      '..kk..kk....',
    ],
    [
      '..k.k....k..',
      '.kbkbk..kbk.',
      '.kwwwwkkkbwk',
      'kKwkwwwwwbk.',
      '.kwwwwwwwwk.',
      '.kbbkkbbkk..',
      '..kk..kk....',
    ],
  ] },
  pet_fox_hop: { w: 12, h: 7, anchor: [6, 5], note: "hop pose; engine lifts it by PETS.hop.px", frames: [
    [
      '..k.k.......',
      '.kbkbk..kkk.',
      '.kwwwwkkbbwk',
      'kKwkwwwwwbk.',
      '.kwwwwwwwwk.',
      '..kbbkbbkk..',
      '...kk.kk....',
    ],
  ] },
  pet_snowman_idle: { w: 9, h: 11, anchor: [4, 9], fps: 2, note: "companion pet (owner only)", frames: [
    [
      '...kkk...',
      '..kjjjk..',
      '.kJjjjJk.',
      '.kwkwkwk.',
      'kkwwccwkk',
      'tkkwwwkkt',
      'ktwwwwwtk',
      'kwwwwwwbk',
      'kwwwwwbbk',
      '.kbbbbbk.',
      '..kkkkk..',
    ],
    [
      'k..kkk..k',
      'tkkjjjkkt',
      'ktJjjjJtk',
      '.kwkwkwk.',
      '.kwwccwk.',
      '..kwwwk..',
      '.kwwwwwk.',
      'kwwwwwwbk',
      'kwwwwwbbk',
      '.kbbbbbk.',
      '..kkkkk..',
    ],
  ] },
  pet_snowman_hop: { w: 9, h: 11, anchor: [4, 9], note: "hop pose; engine lifts it by PETS.hop.px", frames: [
    [
      'k..kkk..k',
      'tkkjjjkkt',
      'ktJjjjJtk',
      '.kwkwkwk.',
      '.kwwccwk.',
      '..kwwwk..',
      '.kwwwwwk.',
      'kwwwwwwbk',
      'kwwwwwbbk',
      '.kbbbbbk.',
      '..kkkkk..',
    ],
  ] },
  back_cape_navy_back: { w: 12, h: 7, anchor: [6, 0], fps: 3, note: "cape, back view; layer front; anchor at BODY_POINTS.neck", frames: [
    [
      '.kKKKKKKKKk.',
      '.kKnKKKKnKk.',
      'kKKnKKKKnKKk',
      'kKKnKKKKnKKk',
      'kKnKKKKKKnKk',
      'kKKnkKKknKKk',
      '.kk..kk..kk.',
    ],
    [
      '.kKKKKKKKKk.',
      '.kKnKKKKnKk.',
      'kKKnKKKKnKKk',
      'kKnKKKKKKnKk',
      'kKnKKKKKKnKk',
      'kkKnKkkKnKkk',
      'k..kk..kk..k',
    ],
  ] },
  back_cape_navy_front: { w: 14, h: 7, anchor: [7, 0], fps: 3, note: "cape, front view; layer behind (edges peek out)", frames: [
    [
      '..kKKKKKKKKk..',
      '.kKKKKKKKKKKk.',
      'kKKKKKKKKKKKKk',
      'kKnKKKKKKKKnKk',
      'kKnKKKKKKKKnKk',
      'knKKKKKKKKKKnk',
      'kkKkkkkkkkkKkk',
    ],
    [
      '..kKKKKKKKKk..',
      '.kKKKKKKKKKKk.',
      'kKKKKKKKKKKKKk',
      'kKnKKKKKKKKnKk',
      'knKKKKKKKKKKnk',
      'knKKKKKKKKKKnk',
      'kKkkkkkkkkkkKk',
    ],
  ] },
  back_cape_gold_back: { w: 12, h: 7, anchor: [6, 0], fps: 3, note: "cape, back view; layer front; anchor at BODY_POINTS.neck", frames: [
    [
      '.kyyTyTyyyk.',
      '.kytTTTytyk.',
      'kyytTyyTtyyk',
      'kyytTTTytyyk',
      'kytyTyyTytyk',
      'kyytTTTktyyk',
      '.kk..kk..kk.',
    ],
    [
      '.kyyTyTyyyk.',
      '.kytTTTytyk.',
      'kyytTyyTtyyk',
      'kytyTTTyytyk',
      'kytyTyyTytyk',
      'kkytTTTytykk',
      'k..kk..kk..k',
    ],
  ] },
  back_cape_gold_front: { w: 14, h: 7, anchor: [7, 0], fps: 3, note: "cape, front view; layer behind (edges peek out)", frames: [
    [
      '..kyyyyyyyyk..',
      '.kyyyyyyyyyyk.',
      'kyyyyyyyyyyyyk',
      'kytyyyyyyyytyk',
      'kytyyyyyyyytyk',
      'ktyyyyyyyyyytk',
      'kkykkkkkkkkykk',
    ],
    [
      '..kyyyyyyyyk..',
      '.kyyyyyyyyyyk.',
      'kyyyyyyyyyyyyk',
      'kytyyyyyyyytyk',
      'ktyyyyyyyyyytk',
      'ktyyyyyyyyyytk',
      'kykkkkkkkkkkyk',
    ],
  ] },
  back_cape_frost_back: { w: 12, h: 7, anchor: [6, 0], fps: 3, note: "cape, back view; layer front; anchor at BODY_POINTS.neck", frames: [
    [
      '.kbbbbbbbbk.',
      '.kbBbbbbBbk.',
      'kbbBbbbbBbbk',
      'kbbBbbbbBbbk',
      'kbBbbbbbbBbk',
      'kbbBkbbkBbbk',
      '.kk..kk..kk.',
    ],
    [
      '.kbbbbbbbbk.',
      '.kbBbbbbBbk.',
      'kbbBbbbbBbbk',
      'kbBbbbbbbBbk',
      'kbBbbbbbbBbk',
      'kkbBbkkbBbkk',
      'k..kk..kk..k',
    ],
  ] },
  back_cape_frost_front: { w: 14, h: 7, anchor: [7, 0], fps: 3, note: "cape, front view; layer behind (edges peek out)", frames: [
    [
      '..kbbbbbbbbk..',
      '.kbbbbbbbbbbk.',
      'kbbbbbbbbbbbbk',
      'kbBbbbbbbbbBbk',
      'kbBbbbbbbbbBbk',
      'kBbbbbbbbbbbBk',
      'kkbkkkkkkkkbkk',
    ],
    [
      '..kbbbbbbbbk..',
      '.kbbbbbbbbbbk.',
      'kbbbbbbbbbbbbk',
      'kbBbbbbbbbbBbk',
      'kBbbbbbbbbbbBk',
      'kBbbbbbbbbbbBk',
      'kbkkkkkkkkkkbk',
    ],
  ] },
  back_scarf_long_back: { w: 10, h: 11, anchor: [2, 1], fps: 5, note: "long flowing scarf tail in TEAM S/s (back view); anchor at BODY_POINTS.neck", frames: [
    [
      '..........',
      'kSSk......',
      'kSSk......',
      'kssk......',
      'ksSkk.....',
      '.kSSsk....',
      '..kSssk...',
      '...kksSkk.',
      '.....kSSsk',
      '......kSsk',
      '.......kk.',
    ],
    [
      '..........',
      'kSSk......',
      'kSSk......',
      'kssk......',
      'ksSk......',
      '.kSSk..k..',
      '..kSskkSk.',
      '...kssSSsk',
      '....ksSksk',
      '.....kk.k.',
      '..........',
    ],
    [
      '..........',
      'kSSk......',
      'kSSk......',
      'kssk......',
      'ksskkk....',
      '.kSSssk...',
      '.kSSssSk..',
      '..kkkkSSk.',
      '......kSsk',
      '.......ksk',
      '........k.',
    ],
  ] },
  back_scarf_long_front: { w: 15, h: 8, anchor: [0, 1], fps: 5, note: "long flowing scarf tail in TEAM S/s (front view); anchor at BODY_POINTS.neck", frames: [
    [
      '..kk...k.......',
      '.kSSkkkSk......',
      '.kSSssSSsk...k.',
      '..kkssSksskkksk',
      '....kkk.ksSSssk',
      '.........kSSsk.',
      '..........kkk..',
      '...............',
    ],
    [
      '..kkkk.........',
      '.kSSssk........',
      '.kSSssSkk.kkkk.',
      '..kkkkSSskSSssk',
      '......kSssSSssk',
      '.......kkskkkk.',
      '.........k.....',
      '...............',
    ],
    [
      '..kkk..........',
      '.kSSsk..kkk....',
      '.kSSsskkssSk...',
      '..kkksSSssSSk..',
      '.....kSSkkkSsk.',
      '......kk...kssk',
      '............ksk',
      '.............k.',
    ],
  ] },
  back_backpack_back: { w: 8, h: 6, anchor: [4, 0], note: "backpack, back view; layer front; anchor at neck", frames: [
    [
      '.kkkkkk.',
      'keeeeeek',
      'kttyyttk',
      'kttttttk',
      'kTttttTk',
      '.kkkkkk.',
    ],
  ] },
  back_backpack_front: { w: 8, h: 3, anchor: [4, 0], note: "backpack straps, front view; layer front", frames: [
    [
      't......t',
      't......t',
      'T......T',
    ],
  ] },
  back_sled_back: { w: 8, h: 9, anchor: [4, 2], note: "wooden sled strapped on the back, back view; layer front; anchor at neck", frames: [
    [
      'kk....kk',
      'nkkkkkkn',
      'neeeeeen',
      'nttttttn',
      'neeeeeen',
      'nttttttn',
      'neeeeeen',
      'nkkkkkkn',
      'kk....kk',
    ],
  ] },
  back_sled_front: { w: 14, h: 8, anchor: [7, 2], note: "sled runners peeking out on both sides, front view; layer behind", frames: [
    [
      'kk..........kk',
      'nk..........kn',
      'n............n',
      'n............n',
      'n............n',
      'n............n',
      'nk..........kn',
      'kk..........kk',
    ],
  ] },
  fx_sparkle: { w: 3, h: 3, anchor: [1, 1], fps: 4, note: "aura_sparkle_ring point", frames: [
    [
      '.w.',
      'wYw',
      '.w.',
    ],
    [
      '...',
      '.Y.',
      '...',
    ],
  ] },
  fx_orbit_flake: { w: 3, h: 3, anchor: [1, 1], fps: 3, note: "aura_orbit_flakes (blue-centred: never mistaken for weather)", frames: [
    [
      '.j.',
      'jwj',
      '.j.',
    ],
    [
      'j.j',
      '.w.',
      'j.j',
    ],
  ] },
  fx_frost_step: { w: 2, h: 2, anchor: [1, 1], note: "aura_frost_steps footprint", frames: [
    [
      'wb',
      'bB',
    ],
  ] },
  trim_fringe_gold: { w: 4, h: 2, anchor: [1, 0], fps: 6, note: "shimmering gold fringe at the scarf tail end; draw at BODY_POINTS.tail", frames: [
    [
      'yY.Y',
      'Y.y.',
    ],
    [
      'Yy.y',
      '.Y.Y',
    ],
    [
      'yYy.',
      'Y.Yy',
    ],
  ] },
  cos_pin_btc: { w: 4, h: 3, anchor: [2, 1], note: "gold coin badge (Bitcoin-bro); draw at HAT_POINTS pin", frames: [
    [
      '.yy.',
      'yTTy',
      '.yy.',
    ],
  ] },
};

// v1.07 wardrobe (DESIGN.md §11). One entry per frame: pin = hat badge point, top = bottom-centre for cos_crown_top.
export const HAT_POINTS = {
  kid_front_idle: [{pin: [7, 2], top: [7, 0]}, {pin: [7, 3], top: [7, 1]}],
  kid_front_windup: [{pin: [7, 2], top: [7, 0]}],
  kid_front_throw: [{pin: [7, 3], top: [7, 1]}, {pin: [7, 3], top: [7, 1]}],
  kid_front_hit: [{pin: [7, 3], top: [7, 1]}, {pin: [8, 2], top: [8, 0]}],
  kid_front_cheer: [{pin: [7, 3], top: [7, 1]}, {pin: [7, 2], top: [7, 0]}],
  kid_front_duck: [{pin: [7, 8], top: [7, 6]}, {pin: [7, 8], top: [7, 6]}],
  kid_back_idle: [{pin: [7, 4], top: [7, 0]}, {pin: [7, 5], top: [7, 1]}],
  kid_back_windup: [{pin: [7, 4], top: [7, 0]}],
  kid_back_throw: [{pin: [7, 4], top: [7, 0]}, {pin: [7, 5], top: [7, 1]}],
  kid_back_hit: [{pin: [7, 4], top: [7, 0]}, {pin: [7, 5], top: [7, 1]}],
  kid_back_cheer: [{pin: [7, 5], top: [7, 1]}, {pin: [7, 4], top: [7, 0]}],
  kid_back_duck: [{pin: [7, 10], top: [7, 6]}, {pin: [7, 10], top: [7, 6]}],
  kid_front_beanie_idle: [{pin: [7, 3], top: [7, 0]}, {pin: [7, 4], top: [7, 1]}],
  kid_front_beanie_cheer: [{pin: [7, 4], top: [7, 1]}, {pin: [7, 3], top: [7, 0]}],
  kid_front_beanie_hit: [{pin: [7, 4], top: [7, 1]}, {pin: [8, 3], top: [8, 0]}],
};

// Owner's kid only: merged over {...PALETTE, ...TEAM_COLORS[team]} when baking kid_* sprites. Mittens use char(s):
export const MITTEN_CHARS = ["y"];
export const COSMETIC_SWAPS = {
  hat_trim_gold: {"h": "#f5b83d"},
  scarf_frost: {"s": "#bfd2ea"},
  scarf_gold: {"s": "#f5b83d"},
  scarf_night: {"s": "#3b4468"},
  mitt_white: {"y": "#ffffff"},
  mitt_pink: {"y": "#ee8f8f"},
  mitt_blue: {"y": "#7fb8ff"},
};

// Snowball trail particle colours (owner only), see DESIGN.md §11.
export const TRAILS = {
  trail_sparks: ["#ffe27a", "#f5b83d", "#f07c34"],
  trail_flakes: ["#ffffff", "#bfd2ea", "#8fa7cf"],
  trail_confetti: ["#ffe27a", "#ee8f8f", "#7fb8ff", "#f07c34"],
};

// Profile frame rings: [main, shade, highlight]; frame_aurora = 3 colours cycled around the ring.
export const FRAMES = {
  frame_silver: ["#bfd2ea", "#8fa7cf", "#ffffff"],
  frame_gold: ["#f5b83d", "#8c5a35", "#ffe27a"],
  frame_aurora: ["#7fb8ff", "#a6e85c", "#ee8f8f"],
};


// v1.08 cosmetics v2 (DESIGN.md §12). BODY_POINTS[sprite][frame] = { neck, tail } for back items / trims.
export const BODY_POINTS = {
  kid_front_idle: [{neck: [7, 8], tail: [4, 11]}, {neck: [7, 9], tail: [4, 11]}],
  kid_front_windup: [{neck: [7, 8], tail: [4, 11]}],
  kid_front_throw: [{neck: [7, 9], tail: [4, 11]}, {neck: [7, 9], tail: [4, 11]}],
  kid_front_hit: [{neck: [7, 9], tail: [4, 12]}, {neck: [8, 8], tail: [5, 11]}],
  kid_front_cheer: [{neck: [7, 9], tail: [4, 11]}, {neck: [7, 8], tail: [4, 10]}],
  kid_front_duck: [{neck: [7, 14], tail: [7, 14]}, {neck: [7, 14], tail: [7, 14]}],
  kid_back_idle: [{neck: [7, 8], tail: [6, 11]}, {neck: [7, 9], tail: [6, 11]}],
  kid_back_windup: [{neck: [7, 8], tail: [6, 11]}],
  kid_back_throw: [{neck: [7, 8], tail: [6, 11]}, {neck: [7, 9], tail: [6, 12]}],
  kid_back_hit: [{neck: [7, 8], tail: [6, 11]}, {neck: [7, 9], tail: [6, 12]}],
  kid_back_cheer: [{neck: [7, 9], tail: [6, 11]}, {neck: [7, 8], tail: [6, 10]}],
  kid_back_duck: [{neck: [7, 14], tail: [6, 15]}, {neck: [7, 14], tail: [6, 15]}],
  kid_front_beanie_idle: [{neck: [7, 8], tail: [4, 11]}, {neck: [7, 9], tail: [4, 11]}],
  kid_front_beanie_cheer: [{neck: [7, 9], tail: [4, 11]}, {neck: [7, 8], tail: [4, 10]}],
  kid_front_beanie_hit: [{neck: [7, 9], tail: [4, 12]}, {neck: [8, 8], tail: [5, 11]}],
};
export const VIEW_OVERLAYS = {
  front: {"snow": "cos_snow_front", "sprites": "kid_front_"},
  back: {"snow": "cos_snow_back", "sprites": "kid_back_"},
  beanie: {"snow": "cos_snow_beanie", "sprites": "kid_front_beanie_"},
};
export const PETS = {
  pet_penguin: {"sprites": {"idle": "pet_penguin_idle", "hop": "pet_penguin_hop"}, "offset": [12, 1], "hop": {"px": 2, "ms": 280, "everyMs": [2500, 6000]}, "name_ru": "\u041f\u0438\u043d\u0433\u0432\u0438\u043d\u0451\u043d\u043e\u043a", "name_en": "Penguin chick"},
  pet_bullfinch: {"sprites": {"idle": "pet_bullfinch_idle", "hop": "pet_bullfinch_hop"}, "offset": [12, 1], "hop": {"px": 2, "ms": 280, "everyMs": [2500, 6000]}, "name_ru": "\u0421\u043d\u0435\u0433\u0438\u0440\u044c", "name_en": "Bullfinch"},
  pet_fox: {"sprites": {"idle": "pet_fox_idle", "hop": "pet_fox_hop"}, "offset": [12, 1], "hop": {"px": 2, "ms": 280, "everyMs": [2500, 6000]}, "name_ru": "\u041f\u0435\u0441\u0435\u0446", "name_en": "Snow fox"},
  pet_snowman: {"sprites": {"idle": "pet_snowman_idle", "hop": "pet_snowman_hop"}, "offset": [12, 1], "hop": {"px": 2, "ms": 280, "everyMs": [2500, 6000]}, "name_ru": "\u0421\u043d\u0435\u0433\u043e\u0432\u0438\u0447\u043e\u043a", "name_en": "Mini snowman"},
};
export const BACK_ITEMS = {
  back_cape_navy: {"back": "back_cape_navy_back", "front": "back_cape_navy_front", "layer": {"back": "front", "front": "behind"}, "attach": "neck"},
  back_cape_gold: {"back": "back_cape_gold_back", "front": "back_cape_gold_front", "layer": {"back": "front", "front": "behind"}, "attach": "neck"},
  back_cape_frost: {"back": "back_cape_frost_back", "front": "back_cape_frost_front", "layer": {"back": "front", "front": "behind"}, "attach": "neck"},
  back_scarf_long: {"back": "back_scarf_long_back", "front": "back_scarf_long_front", "layer": {"back": "front", "front": "behind"}, "attach": "neck"},
  back_backpack: {"back": "back_backpack_back", "front": "back_backpack_front", "layer": {"back": "front", "front": "front"}, "attach": "neck"},
  back_sled: {"back": "back_sled_back", "front": "back_sled_front", "layer": {"back": "front", "front": "behind"}, "attach": "neck"},
};
export const AURAS = {
  aura_sparkle_ring: {"type": "ring", "colors": ["#ffffff", "#ffe27a"], "sprite": "fx_sparkle", "count": 5, "rx": 9, "ry": 3, "cy": 0, "periodMs": 3200, "name_ru": "\u0418\u0441\u043a\u0440\u0438\u0441\u0442\u043e\u0435 \u043a\u043e\u043b\u044c\u0446\u043e", "name_en": "Sparkle ring"},
  aura_glow_gold: {"type": "outline", "colors": ["#ffe27a", "#f5b83d"], "pulseMs": 600, "from": "neck", "name_ru": "\u0417\u043e\u043b\u043e\u0442\u043e\u0435 \u0441\u0438\u044f\u043d\u0438\u0435", "name_en": "Gold glow"},
  aura_glow_frost: {"type": "outline", "colors": ["#ffffff", "#bfd2ea"], "pulseMs": 600, "from": "neck", "name_ru": "\u041c\u043e\u0440\u043e\u0437\u043d\u043e\u0435 \u0441\u0438\u044f\u043d\u0438\u0435", "name_en": "Frost glow"},
  aura_orbit_flakes: {"type": "particles", "mode": "orbit", "sprite": "fx_orbit_flake", "colors": ["#ffffff", "#7fb8ff"], "count": 3, "rx": 10, "ry": 4, "cyFrom": "neck", "cy": 3, "periodMs": 2400, "name_ru": "\u0425\u043e\u0440\u043e\u0432\u043e\u0434 \u0441\u043d\u0435\u0436\u0438\u043d\u043e\u043a", "name_en": "Orbiting flakes"},
  aura_frost_steps: {"type": "particles", "mode": "steps", "sprite": "fx_frost_step", "colors": ["#bfd2ea", "#8fa7cf"], "everyPx": 4, "lifeMs": 1200, "max": 6, "name_ru": "\u041c\u043e\u0440\u043e\u0437\u043d\u044b\u0435 \u0441\u043b\u0435\u0434\u044b", "name_en": "Frost steps"},
};
export const TRIMS = {
  trim_fringe_gold: {"type": "sprite", "sprite": "trim_fringe_gold", "at": "tail", "fps": 6, "name_ru": "\u0417\u043e\u043b\u043e\u0442\u0430\u044f \u0431\u0430\u0445\u0440\u043e\u043c\u0430", "name_en": "Gold fringe"},
  trim_mitt_glow: {"type": "swapCycle", "char": "y", "colors": ["#ffe27a", "#f5b83d", "#ffffff"], "stepMs": 250, "name_ru": "\u0421\u0438\u044f\u044e\u0449\u0438\u0435 \u0432\u0430\u0440\u0435\u0436\u043a\u0438", "name_en": "Glowing mittens"},
};
export const LOOKS = {
  look_northern_lights: {"name_ru": "\u0421\u0435\u0432\u0435\u0440\u043d\u043e\u0435 \u0441\u0438\u044f\u043d\u0438\u0435", "name_en": "Northern Lights", "tier": "premium", "items": {"pet": "pet_fox", "back": "back_cape_frost", "aura": "aura_orbit_flakes", "trim": "trim_mitt_glow", "swaps": ["scarf_frost"], "frame": "frame_aurora", "trail": "trail_flakes"}},
  look_ice_king: {"name_ru": "\u041b\u0435\u0434\u044f\u043d\u043e\u0439 \u043a\u043e\u0440\u043e\u043b\u044c", "name_en": "Ice King", "tier": "premium", "items": {"hat": "cos_crown_top", "pet": "pet_penguin", "back": "back_cape_navy", "aura": "aura_sparkle_ring", "trim": "trim_fringe_gold", "swaps": ["mitt_white"], "frame": "frame_silver", "trail": "trail_sparks"}},
  look_snow_whale: {"name_ru": "\u0421\u043d\u0435\u0436\u043d\u044b\u0439 \u043a\u0438\u0442", "name_en": "Snow Whale", "tier": "free", "unlock": "ach:whale_survivor", "items": {"hat": "cos_pin_whale", "pet": "pet_snowman", "back": "back_scarf_long", "aura": "aura_frost_steps", "swaps": ["scarf_night", "mitt_blue"], "trail": "trail_flakes"}},
  look_btc_bro: {"name_ru": "\u0411\u0438\u0442\u043a\u043e\u0438\u043d-\u0431\u0440\u043e", "name_en": "Bitcoin Bro", "tier": "premium", "items": {"hat": "cos_pin_btc", "pet": "pet_bullfinch", "back": "back_cape_gold", "aura": "aura_glow_gold", "trim": "trim_fringe_gold", "swaps": ["hat_trim_gold"], "frame": "frame_gold", "trail": "trail_sparks"}},
  look_backyard: {"name_ru": "\u0414\u0432\u043e\u0440\u043e\u0432\u044b\u0439 \u0433\u0435\u0440\u043e\u0439", "name_en": "Backyard Hero", "tier": "free", "unlock": "lv:5", "items": {"pet": "pet_bullfinch", "back": "back_backpack", "aura": "aura_frost_steps", "swaps": ["mitt_pink"]}},
};

export const UI = {
  "fonts": {
    "display": "'Press Start 2P', monospace",
    "body": "'Tiny5', 'Press Start 2P', monospace",
    "css": "https://fonts.googleapis.com/css2?family=Press+Start+2P&family=Tiny5&display=swap"
  },
  "colors": {
    "pageBg": "#10142a",
    "panel": "#1a1c2c",
    "panelAlpha": "rgba(26,28,44,0.88)",
    "panelBorder": "#5d6f9e",
    "panelHighlight": "#8fa7cf",
    "panelShadow": "#0b0d18",
    "text": "#f4f8ff",
    "textDim": "#8fa7cf",
    "up": "#a6e85c",
    "down": "#ff5d6c",
    "green": "#a6e85c",
    "greenDark": "#4fa446",
    "red": "#d63a4f",
    "redDark": "#8a1f3c",
    "neutral": "#bfd2ea",
    "gold": "#ffe27a",
    "goldDark": "#f5b83d",
    "demo": "#f5b83d",
    "live": "#a6e85c",
    "whale": "#7fb8ff",
    "liq": "#ffe27a",
    "signText": "#573522",
    "snow": "#e4eef8",
    "trench": "#5d6f9e",
    "rope": "#dcb784",
    "shakeFlash": "rgba(255,255,255,0.35)"
  },
  "sizes": {
    "price": 16,
    "priceWide": 24,
    "label": 8,
    "body": 16,
    "feed": 16,
    "banner": 14,
    "bannerWide": 24,
    "panelBorder": 2,
    "pressureBarH": 10
  },
  "rarity": {
    "common": "#8fa7cf",
    "rare": "#7fb8ff",
    "epic": "#f07c34",
    "legendary": "#f5b83d",
    "legendaryShine": "#ffe27a"
  },
  "achLocked": "#5d6f9e",
  "miniFont": {
    "w": 3,
    "h": 5,
    "advance": 4,
    "glyphs": {
      "0": [
        "###",
        "#.#",
        "#.#",
        "#.#",
        "###"
      ],
      "1": [
        ".#.",
        "##.",
        ".#.",
        ".#.",
        "###"
      ],
      "2": [
        "###",
        "..#",
        "###",
        "#..",
        "###"
      ],
      "3": [
        "###",
        "..#",
        ".##",
        "..#",
        "###"
      ],
      "4": [
        "#.#",
        "#.#",
        "###",
        "..#",
        "..#"
      ],
      "5": [
        "###",
        "#..",
        "###",
        "..#",
        "###"
      ],
      "6": [
        "###",
        "#..",
        "###",
        "#.#",
        "###"
      ],
      "7": [
        "###",
        "..#",
        "..#",
        ".#.",
        ".#."
      ],
      "8": [
        "###",
        "#.#",
        "###",
        "#.#",
        "###"
      ],
      "9": [
        "###",
        "#.#",
        "###",
        "..#",
        "###"
      ],
      ".": [
        "...",
        "...",
        "...",
        "...",
        ".#."
      ],
      ",": [
        "...",
        "...",
        "...",
        ".#.",
        "#.."
      ],
      "-": [
        "...",
        "...",
        "###",
        "...",
        "..."
      ],
      "+": [
        "...",
        ".#.",
        "###",
        ".#.",
        "..."
      ],
      "%": [
        "#.#",
        "..#",
        ".#.",
        "#..",
        "#.#"
      ],
      "$": [
        ".##",
        "##.",
        ".#.",
        ".##",
        "##."
      ],
      "k": [
        "#..",
        "#.#",
        "##.",
        "#.#",
        "#.#"
      ],
      "K": [
        "#.#",
        "#.#",
        "##.",
        "#.#",
        "#.#"
      ],
      " ": [
        "...",
        "...",
        "...",
        "...",
        "..."
      ]
    }
  },
  "signText": {
    "origin": [
      3,
      2
    ],
    "maxChars": 5,
    "color": "#573522"
  }
};
